UPDATE game_config SET key_word = '我的传奇,wodechuanqi,wdcq' WHERE pack_name='com.wdcq.ltg' AND type='1';
UPDATE game_config SET key_word = '复古传奇,fuguchuanqi,fgcq' WHERE pack_name='com.sanjiuyx.gzwd' AND type='1';
UPDATE game_config SET key_word = '神武3,神武3手游,shenwu3,sw3,神武2,shenwu2,sw2' WHERE pack_name='com.duoyi.shenwu,com.hero.shenwu,com.duoyi.shenwu3' AND type='1';
UPDATE game_config SET key_word = '传说对决(台服),Arena of Valor (TW),chuanshuoduijue(taifu),csdj(tf),传说对决,chuanshuoduijue,csdj,傳說對決,moba,lol,王者荣耀台服,wangzherongyao,wzry,Garena,开黑' WHERE pack_name='com.garena.game.kgtw,com.garena.game.kgtwtest' AND type='1';
UPDATE game_config SET key_word = '第五人格(国服),Identity V (CN),diwurenge(guofu),dwrg(gf),第五人格,Identity 5,diwurenge,dwrg,网易,wangyi,wy,黎明杀机' WHERE pack_name='com.netease.dwrg,com.tencent.tmgp.dwrg' AND type='1';
UPDATE game_config SET key_word = '楚留香,chuliuxiang,clx,网易,wangyi,wy' WHERE pack_name='com.netease.wyclx' AND type='1';
UPDATE game_config SET key_word = '圣斗士星矢(腾讯),shengdoushixingshi(tengxun),sdsxs(tx)' WHERE pack_name='com.tencent.tmgp.sskgame' AND type='1';
UPDATE game_config SET key_word = '封仙域,fengxianyu,fxy' WHERE pack_name='com.yinhu.sdk.fxy.pj' AND type='1';
UPDATE game_config SET key_word = '武神赵子龙,wushenzhaozilong,wszzl' WHERE pack_name='com.yaowan.wszzl.miyu.blockgame' AND type='1';
UPDATE game_config SET key_word = '魔灵宝贝,molingbaobei,mlbb' WHERE pack_name='cn.miyugame.mlzh.blockgame' AND type='1';
UPDATE game_config SET key_word = '刺激战场(国服),PUBG Mobile (CN),cijizhanchang(guofu),cjzc(gf),刺激战场,cijizhanchang,cjzc,绝地求生:刺激战场,juedeqiusheng:cijizhanchang,jdqs:cjzc,吃鸡,chiji' WHERE pack_name='com.tencent.tmgp.pubgmhd' AND type='1';
UPDATE game_config SET key_word = '阴阳师,Onmyoji (CN),yinyangshi,yys,Onmyoji,网易,wangyi,wy,陰陽師,ssr' WHERE pack_name='com.tencent.tmgp.yys.zqb,com.netease.onmyoji,com.onmyoji.hmt2' AND type='1';
UPDATE game_config SET key_word = '大航海之路,dahanghaizhilu,dhhzl,网易,wangyi,wy' WHERE pack_name='com.tencent.tmgp.dhhzl.zqb,com.netease.dhhzl' AND type='1';
UPDATE game_config SET key_word = '刺激战场(亚服),PUBG Mobile (AS),cijizhanchang(yafu),cjzc(yf),绝地求生:刺激战场(亚服),juedeqiusheng:cijizhanchang(yafu),jdqs:cjzc(yf),絕地求生:刺激戰場国际版,吃鸡,大逃杀' WHERE pack_name='com.tencent.ig' AND type='1';
UPDATE game_config SET key_word = '刺激战场(日韩),PUBG Mobile (KR&JP),cijizhanchang(rihan),cjzc(rh),배틀그라운드,绝地求生:刺激战场,大逃杀,jdqs,dts,吃鸡,chiji,韩服,日服' WHERE pack_name='com.pubg.krmobile,com.tencent.ig' AND type='1';
UPDATE game_config SET key_word = '荒野乱斗,Brawl Stars,huangyeluandou,hyld,Supercell卡牌竞技' WHERE pack_name='com.supercell.brawlstars' AND type='1';
UPDATE game_config SET key_word = '潮人篮球,Fever Basketball,chaorenlanqiu,crlq,FBGame' WHERE pack_name='com.netease.lh01' AND type='1';
UPDATE game_config SET key_word = '天命之子(韩服),Destiny Child (KR),tianmingzhizi(hanfu),tmzz(hf),데스티니 차일드,데스티니 차일드 for kakao,destiny child' WHERE pack_name='com.NextFloor.DestinyChild' AND type='1';
UPDATE game_config SET key_word = '堡垒之夜(澳服),Fortnite Battle Royale(AU),baoleizhiye(aofu),blzy(af),堡垒之夜手游(澳服),baoleizhiyeshouyou(aofu),blzysy(af)' WHERE pack_name='com.epicgames.fortnite' AND type='1';
UPDATE game_config SET key_word = '堡垒之夜(美服),Fortnite Battle Royale(US),baoleizhiye(meifu),blzy(mf),堡垒之夜手游(美服),baoleizhiyeshouyou(meifu),blzysy(mf)' WHERE pack_name='com.epicgames.fortnite' AND type='1';
UPDATE game_config SET key_word = '堡垒之夜(欧服),Fortnite Battle Royale(EU),baoleizhiye(oufu),blzy(of),堡垒之夜手游(欧服),baoleizhiyeshouyou(oufu),blzysy(of)' WHERE pack_name='com.epicgames.fortnite' AND type='1';
UPDATE game_config SET key_word = '堡垒之夜(亚服),Fortnite Battle Royale(AS),baoleizhiye(yafu),blzy(yf),堡垒之夜,Fortnite Battle Royale,baoleizhiye,blzy,FortCraft,要塞英雄：大逃殺' WHERE pack_name='com.epicgames.fortnite' AND type='1';
UPDATE game_config SET key_word = '三国杀名将传,sanguoshamingjiangchuan,sgsmjc' WHERE pack_name='com.sanguosha.mjz' AND type='1';
UPDATE game_config SET key_word = '率土之滨,lvtuzhibin,ltzb,shuaituzhibin,网易率土之滨,wangyilvtuzhibin,wyltzb,wangyishuaituzhibin,wystzb' WHERE pack_name='com.tencent.tmgp.stzb,com.netease.stzb' AND type='1';
UPDATE game_config SET key_word = '光明大陆,Land of Glory (CN),guangmingdalu,gmdl,网易光明大陆,wangyiguangmingdalu,wygmdl,Land of glory' WHERE pack_name='com.tencent.tmgp.gmdl,com.netease.gmdl' AND type='1';
UPDATE game_config SET key_word = '大话西游,dahuaxiyou,dhxy,网易大话西游,wangyidahuaxiyou,wydhxy' WHERE pack_name='com.netease.dhxy.sy37,com.netease.dhxy' AND type='1';
UPDATE game_config SET key_word = '蜀门手游,shumenshouyou,smsy' WHERE pack_name='com.ycgame.t11' AND type='1';
UPDATE game_config SET key_word = '魔域手游,moyushouyou,mysy' WHERE pack_name='com.westhouse.mysjb.xsj,com.tq.my' AND type='1';
UPDATE game_config SET key_word = '苍之纪元,cangzhijiyuan,czjy' WHERE pack_name='com.ylbgj.rastar' AND type='1';
UPDATE game_config SET key_word = '屠龙战城,tulongzhancheng,tlzc' WHERE pack_name='com.sjyou.xy602' AND type='1';
UPDATE game_config SET key_word = '最终王冠,zuizhongwangguan,zzwg' WHERE pack_name='com.xindong.thelastcrown' AND type='1';
UPDATE game_config SET key_word = '次元前线,ciyuanqianxian,cyqx' WHERE pack_name='cn.mlong.cos.miyu.blockgame' AND type='1';
UPDATE game_config SET key_word = '圣斗士星矢：重生,shengdoushixingshi：zhongsheng,sdsxs：zs' WHERE pack_name='com.denachina.g10000001.denacn' AND type='1';
UPDATE game_config SET key_word = '笑傲乾坤,xiaoaoqiankun,xaqk' WHERE pack_name='com.kkwan.yjyh.hyww' AND type='1';
UPDATE game_config SET key_word = '永远的7日之都,yongyuande7rizhidou,yyd7rzd,网易,wangyi,wy' WHERE pack_name='com.netease.qrzd,com.jinwan.yyd7rzd.x7sy,com.tencent.tmgp.yongyong.yydqrzd' AND type='1';
UPDATE game_config SET key_word = '决战！平安京,Onmyoji Arena (CN),juezhan！pinganjing,jz！paj,决战!平安京,juezhan!pinganjing,jz!paj,Onmyoji Arena,阴阳师MOBA,开黑' WHERE pack_name='com.netease.moba,com.tencent.tmgp.kaopu.jzpaj,com.shouyou.jzpaj.bg' AND type='1';
UPDATE game_config SET key_word = '方舟:生存进化,ARK: Survival Evolved,fangzhou:shengcunjinhua,fz:scjh' WHERE pack_name='com.studiowildcard.wardrumstudios.ark' AND type='1';
UPDATE game_config SET key_word = '梦幻模拟战,menghuanmonizhan,mhmnz' WHERE pack_name='com.zlongame.mhmnz.mumu' AND type='1';
UPDATE game_config SET key_word = '终结者2:审判日,Rules of Survival (CN),zhongjiezhe2:shenpanri,zjz2:spr,电影官方大逃杀手游,荒野大逃杀,吃鸡,网易,netease,pubg,绝地求生,Rules of Survival,ros' WHERE pack_name='com.netease.zjz,com.tencent.tmgp.yongyong.zjz,com.netease.zjz2.nearme.gamecenter' AND type='1';
UPDATE game_config SET key_word = '镇魔曲,镇魔曲手游,zhenmoqu,zmq,网易镇魔曲,wangyizhenmoqu,wyzmq' WHERE pack_name='com.netease.zmq,com.tencent.tmgp.yinhan.zmq' AND type='1';
UPDATE game_config SET key_word = 'Fate/GO(日服),Fate/GO (JP),Fate/GO(rifu),Fate/GO(rf),Fate/GO 日服,Fate/GO rifu,Fate/GO rf,FateGrandOrder日服,FateGrandOrderrifu,FateGrandOrderrf,fgo,fatego,rifu' WHERE pack_name='com.aniplex.fategrandorder' AND type='1';
UPDATE game_config SET key_word = 'QQ飞车,QQfeiche,QQfc,QQ飞车(删档测试版),GKART (Close Beta),QQfeiche(shandangceshiban),QQfc(sdcsb)' WHERE pack_name='com.tencent.tmgp.speedmobile' AND type='1';
UPDATE game_config SET key_word = '全军出击,PUBG Mobile by TiMi (CN),quanjunchuji,qjcj,绝地求生:全军出击,juedeqiusheng:quanjunchuji,jdqs:qjcj,绝地求生 全军出击,juedeqiusheng quanjunchuji,jdqs qjcj,吃鸡,chiji' WHERE pack_name='com.tencent.tmgp.pubgm' AND type='1';
UPDATE game_config SET key_word = '叛逆性百万亚瑟王,pannixingbaiwanyasewang,pnxbwysw,网易,wangyi,wy' WHERE pack_name='com.tencent.tmgp.zqgame.ma,com.netease.pnxbwysw' AND type='1';
UPDATE game_config SET key_word = '影之诗,影之诗(网易版),yingzhishi,yzs,shadowverse,网易,wangyi,wy' WHERE pack_name='com.netease.yzs,com.tencent.tmgp.yongyong.yzs' AND type='1';
UPDATE game_config SET key_word = '天下,tianxia,tx,网易天下,wangyitianxia,wytx' WHERE pack_name='com.tencent.tmgp.tx,com.netease.tx' AND type='1';
UPDATE game_config SET key_word = '山海经3D,shanhaijing3D,shj3D' WHERE pack_name='com.askj.jtyl11.ewan.jingqi' AND type='1';
UPDATE game_config SET key_word = '魔域来了,moyulaile,myll' WHERE pack_name='com.xy.moyuguilai' AND type='1';
UPDATE game_config SET key_word = '猎魂觉醒,The Soul of Hunter (CN),liehunjuexing,lhjx,网易,wangyi,wy' WHERE pack_name='com.netease.AVALON,com.tencent.tmgp.lewu.lhjx,com.jinwan.lhjx.x7sy' AND type='1';
UPDATE game_config SET key_word = '刺激战场(美服),PUBG Mobile (US),cijizhanchang(meifu),cjzc(mf),绝地求生:刺激战场(美服),juedeqiusheng:cijizhanchang(meifu),jdqs:cjzc(mf),PUBG Mobile,絕地求生:刺激戰場国际版,吃鸡,大逃杀' WHERE pack_name='com.tencent.ig' AND type='1';
UPDATE game_config SET key_word = '舰无虚发:暗星,jianwuxufa:anxing,jwxf:ax,网易,wangyi,wy' WHERE pack_name='com.netease.jwxfax,com.tencent.tmgp.yongyong.jwxf,com.netease.faro' AND type='1';
UPDATE game_config SET key_word = '魔力宝贝,魔力宝贝手机版,molibaobei,mlbb,molibaobeishoujiban,mlbbsjb' WHERE pack_name='com.tencent.crossgate' AND type='1';
UPDATE game_config SET key_word = '传奇来了,chuanqilaile,cqll' WHERE pack_name='com.shengtu.cqllh5.yyfx,com.huimee.dabaoapp' AND type='1';
UPDATE game_config SET key_word = '青云奇侠传,qingyunqixiachuan,qyqxc' WHERE pack_name='com.sjyy.qyxxz' AND type='1';
UPDATE game_config SET key_word = '大唐无双,大唐无双手游,datangwushuang,dtws,网易大唐无双,wangyidatangwushuang,wydtws' WHERE pack_name='com.tencent.tmgp.dtws,com.netease.dtws' AND type='1';
UPDATE game_config SET key_word = '无尽对决,Mobile Legends,wujinduijue,wjdj,Mobile Legends：bang bang,外服MOBA,ML,王者荣耀LOL,开黑' WHERE pack_name='com.mobile.legends' AND type='1';
UPDATE game_config SET key_word = '梦幻西游,梦幻西游手游,menghuanxiyou,mhxy,网易梦幻西游,wangyimenghuanxiyou,wymhxy' WHERE pack_name='com.netease.my' AND type='1';
UPDATE game_config SET key_word = 'Twitch,直播' WHERE pack_name='tv.twitch.android.app' AND type='1';
UPDATE game_config SET key_word = '倩女幽魂,倩女幽魂手游,qiannvyouhun,qnyh,网易倩女幽魂,wangyiqiannvyouhun,wyqnyh' WHERE pack_name='com.netease.qnyh,com.tencent.tmgp.l10,com.netease.l10' AND type='1';
UPDATE game_config SET key_word = '孤岛先锋,gudaoxianfeng,gdxf,wangyi,网易,wy' WHERE pack_name='com.netease.gd,com.tencent.tmgp.yongyong.gdxf' AND type='1';
UPDATE game_config SET key_word = '魔法禁书目录,A Certain Magical Index,mofajinshumulu,mfjsml,网易,wangyi,wy' WHERE pack_name='com.tencent.tmgp.yongyong.mfjs,com.netease.index,com.shouyou.mfjsml.guopan,com.netease.mfjsml.yyxx.tt' AND type='1';
UPDATE game_config SET key_word = '汉王纷争,hanwangfenzheng,hwfz,网易,wangyi,wy' WHERE pack_name='com.netease.hwfz,com.tencent.tmgp.yongyong.hwfz' AND type='1';
UPDATE game_config SET key_word = '魂之轨迹,hunzhiguiji,hzgj,网易,wangyi,wy' WHERE pack_name='com.netease.hzgj' AND type='1';
UPDATE game_config SET key_word = '九州·海上牧云记,jiuzhou·haishangmuyunji,jz·hsmyj,网易,wangyi,wy' WHERE pack_name='com.tencent.tmgp.yongyong.jzhsmyj,com.netease.hsmyj' AND type='1';
UPDATE game_config SET key_word = '我叫MT4,wojiaoMT4,wjMT4' WHERE pack_name='com.tencent.tmgp.mt4' AND type='1';
UPDATE game_config SET key_word = '新剑侠情缘,Sword Heroes’ Fate,xinjianxiaqingyuan,xjxqy,剑侠情缘,jianxiaqingyuan,jxqy' WHERE pack_name='com.tencent.tmgp.jxqy' AND type='1';
UPDATE game_config SET key_word = '自由幻想,ziyouhuanxiang,zyhx' WHERE pack_name='com.tencent.tmgp.ffom' AND type='1';
UPDATE game_config SET key_word = '乱世王者,luanshiwangzhe,lswz' WHERE pack_name='com.tencent.tmgp.wec' AND type='1';
UPDATE game_config SET key_word = '开心消消乐,kaixinxiaoxiaole,kxxxl,休闲益智' WHERE pack_name='com.happyelements.AndroidAnimal' AND type='1';
UPDATE game_config SET key_word = '穿越火线,CrossFire Mobile (CN),chuanyuehuoxian,cyhx,腾讯穿越火线枪战王者,tenxunchuanyuehuoxian,txcyhx,Cross Fire,cffps,射击,CF,fps,CrossFire Legends' WHERE pack_name='com.tencent.tmgp.cf' AND type='1';
UPDATE game_config SET key_word = '风之大陆,fengzhidalu,fzdl' WHERE pack_name='com.zlongame.fzdl,com.tencent.tmgp.fzdl,com.zlongame.fzdl.guopan' AND type='1';
UPDATE game_config SET key_word = 'QQ炫舞,QQ炫舞手游,QQxuanwu,QQxw' WHERE pack_name='com.tencent.tmgp.qqx5' AND type='1';
UPDATE game_config SET key_word = '魂斗罗:归来,hundouluo:guilai,hdl:gl' WHERE pack_name='com.tencent.shootgame' AND type='1';
UPDATE game_config SET key_word = '天龙八部,tianlongbabu,tlbb' WHERE pack_name='com.tencent.tmgp.tstl' AND type='1';
UPDATE game_config SET key_word = '欢乐斗地主,huanledoudezhu,hlddz,斗地主' WHERE pack_name='com.qqgame.hlddz' AND type='1';
UPDATE game_config SET key_word = '问道,wendao,wd' WHERE pack_name='com.tencent.tmgp.gbits.atm,com.gbits.atm' AND type='1';
UPDATE game_config SET key_word = 'FIFA足球世界,FIFA Mobile,FIFAzuqiushijie,FIFAzqsj' WHERE pack_name='com.tencent.fifamobile' AND type='1';
UPDATE game_config SET key_word = '王国纪元,Lords Mobile,wangguojiyuan,wgjy,lords mobile' WHERE pack_name='com.igg.android.lordsmobile,com.igg.ios.lordsmobile,com.igg.android.lordsmobile_cn' AND type='1';
UPDATE game_config SET key_word = '剑与家园,jianyujiayuan,jyjy,art of conquest' WHERE pack_name='com.tencent.tmgp.lilithgame.sgame' AND type='1';
UPDATE game_config SET key_word = '皇室战争,Clash Royale,huangshizhanzheng,hszz,部落冲突：皇室战争' WHERE pack_name='com.wdj.supercell.clashroyale.yixin,com.tencent.tmgp.supercell.clashroyale,com.supercell.clashroyale' AND type='1';
UPDATE game_config SET key_word = '奇迹MU:觉醒,qijiMU:juexing,qjMU:jx' WHERE pack_name='com.tencent.tmgp.tmsk.qj2' AND type='1';
UPDATE game_config SET key_word = '火影忍者,huoyingrenzhe,hyrz' WHERE pack_name='com.tencent.KiHan' AND type='1';
UPDATE game_config SET key_word = 'QQ华夏,QQ华夏手游,QQhuaxia,QQhx,QQhuaxiashouyou,QQhxsy' WHERE pack_name='com.tencent.hxgame' AND type='1';
UPDATE game_config SET key_word = '诛仙,zhuxian,zx' WHERE pack_name='com.tencent.tmgp.zhuxian' AND type='1';
UPDATE game_config SET key_word = '欢乐麻将全集,huanlemajiangquanji,hlmjqj' WHERE pack_name='com.qqgame.happymj' AND type='1';
UPDATE game_config SET key_word = '龙之谷,longzhigu,lzg,腾讯龙之谷,tenxunlongzhigu,txlzg,dn,dragon nest' WHERE pack_name='com.tencent.tmgp.dragonnest' AND type='1';
UPDATE game_config SET key_word = '境界-死神激斗,jingjie-sishenjidou,jj-ssjd,境界,境界-死神激斗（正版授权）,jingjie,jj,jingjie-sishenjidou（zhengbanshouquan）,jj-ssjd（zbsq）,jjssjd' WHERE pack_name='com.denachina.g13002008.denacn,com.cmge.ssjd.m4399,com.cmge.ssjd.baidu,com.cmge.ssjd.aligames,com.cmge.ssjd.mz,com.tencent.tmgp.cmge.ssjd,com.cmge.ssjd.qihoo,com.ssjd.mi,com.ssjd.cmge' AND type='1';
UPDATE game_config SET key_word = '实况足球,shikuangzuqiu,skzq,PES2018,世界杯,网易,wangyi,wy' WHERE pack_name='com.netease.pes' AND type='1';
UPDATE game_config SET key_word = '崩坏3,Honkai Impact 3 (CN),benghuai3,bh3' WHERE pack_name='com.tencent.tmgp.bh3,com.miHoYo.enterprise.NGHSoD,com.miHoYo.bh3' AND type='1';
UPDATE game_config SET key_word = '电击文库：零境交错,dianjiwenku：lingjingjiaocuo,djwk：ljjc' WHERE pack_name='com.tencent.tmgp.fcicv' AND type='1';
UPDATE game_config SET key_word = '部落冲突,Clash of Clans,buluochongtu,blct,coc' WHERE pack_name='com.supercell.clashofclans,com.tencent.tmgp.supercell.clashofclans,com.darksoulcoc.clashofclans1,com.clashology.sv1clash,ru.cocbuilder.wrapperhideout.b5,cc.royalwar.cocs1,com.joke.coc,nullsclash.night.rel' AND type='1';
UPDATE game_config SET key_word = '流星蝴蝶剑,liuxinghudiejian,lxhdj,网易,wangyi,wy' WHERE pack_name='com.netease.liuxinghudiejian,com.netease.lx12,com.tencent.tmgp.lx12' AND type='1';
UPDATE game_config SET key_word = '轩辕传奇,xuanyuanchuanqi,xycq' WHERE pack_name='com.tencent.tmgp.xymobile' AND type='1';
UPDATE game_config SET key_word = '武林外传,武林外传手游,wulinwaichuan,wlwc' WHERE pack_name='com.pwrd.wlwz.laohu' AND type='1';
UPDATE game_config SET key_word = '御龙在天,yulongzaitian,ylzt' WHERE pack_name='com.tencent.tmgp.ylm' AND type='1';
UPDATE game_config SET key_word = '剑侠世界2,jianxiashijie2,jxsj2' WHERE pack_name='com.tencent.tmgp.jxsj2' AND type='1';
UPDATE game_config SET key_word = '魔法门之英雄无敌:战争纪元,mofamenzhiyingxiongwudi:zhanzhengjiyuan,mfmzyxwd:zzjy' WHERE pack_name='com.tencent.tmgp.yxwdzzjy' AND type='1';
UPDATE game_config SET key_word = '三国如龙传,sanguorulongchuan,sgrlc,网易,wangyi,wy' WHERE pack_name='com.tencent.tmgp.sgrlz,com.netease.sgrlz.' AND type='1';
UPDATE game_config SET key_word = '球球大作战,qiuqiudazuozhan,qqdzz,Battle of Balls' WHERE pack_name='com.ztgame.bob' AND type='1';
UPDATE game_config SET key_word = '寻仙,xunxian,xx' WHERE pack_name='com.tencent.tmgp.xxsy' AND type='1';
UPDATE game_config SET key_word = '最强NBA,zuiqiangNBA,zqNBA' WHERE pack_name='com.tencent.tmgp.NBA' AND type='1';
UPDATE game_config SET key_word = '炉石传说,lushichuanshuo,lscs,Hearthstone' WHERE pack_name='com.blizzard.wtcg.hearthstone,com.blizzard.wtcg.cn.hearthstone' AND type='1';
UPDATE game_config SET key_word = '少女前线,Girls’ Frontline,shaonvqianxian,snqx' WHERE pack_name='com.digitalsky.girlsfrontline.cn,com.tencent.tmgp.girlsfrontline' AND type='1';
UPDATE game_config SET key_word = '真龙霸业,zhenlongbaye,zlby' WHERE pack_name='com.tencent.tmgp.zlong' AND type='1';
UPDATE game_config SET key_word = '航海王 启航,hanghaiwang qihang,hhw qh,ONE PIECE' WHERE pack_name='com.tencent.tmgp.g12000128,cn.mobage.g12000128' AND type='1';
UPDATE game_config SET key_word = 'Fate/GO 国服,Fate/GO guofu,Fate/GO gf,fate grand order,冠位指定,命运,fate/grand order,fgo,mingyunguanweizhiding,fatego' WHERE pack_name='com.tencent.tmgp.fgo,com.bilibili.fatego' AND type='1';
UPDATE game_config SET key_word = '全民飞机大战,quanminfeijidazhan,qmfjdz' WHERE pack_name='com.tencent.feiji' AND type='1';
UPDATE game_config SET key_word = '忍者必须死3,renzhebixusi3,rzbxs3' WHERE pack_name='com.pandadastudio.ninjamustdie3' AND type='1';
UPDATE game_config SET key_word = '奇迹暖暖,qijinuannuan,qjnn' WHERE pack_name='com.tencent.tmgp.qjnn' AND type='1';
UPDATE game_config SET key_word = '少年三国志,shaoniansanguozhi,snsgz' WHERE pack_name='com.youzu.android.snsgz,com.tencent.tmgp.snsgz' AND type='1';
UPDATE game_config SET key_word = '永恒纪元,yonghengjiyuan,yhjy,AION' WHERE pack_name='com.tencent.tmgp.dtszj,com.sy.yhxmz.cn' AND type='1';
UPDATE game_config SET key_word = '漫威:未来之战,manwei:weilaizhizhan,mw:wlzz,复仇者联盟3,复联3' WHERE pack_name='com.tencent.tmgp.mff' AND type='1';
UPDATE game_config SET key_word = '拳皇命运,quanhuangmingyun,qhmy' WHERE pack_name='com.tencent.kof' AND type='1';
UPDATE game_config SET key_word = '三国杀,sanguosha,sgs' WHERE pack_name='bf.sgs.hdexp,com.sgshd.nearme.gamecenter' AND type='1';
UPDATE game_config SET key_word = '放开那三国2,fangkainasanguo2,fknsg2' WHERE pack_name='apps-com.babeltime.fknsg2.wdj,com.tencent.tmgp.fknsg2,com.babeltime.sg2.zyx' AND type='1';
UPDATE game_config SET key_word = '龙珠激斗,longzhujidou,lzjd' WHERE pack_name='com.tencent.tmgp.dragonball' AND type='1';
UPDATE game_config SET key_word = '碧蓝航线,Azur Lane,bilanhangxian,blhx' WHERE pack_name='com.tencent.tmgp.bilibili.blhx,com.bilibili.azurlane' AND type='1';
UPDATE game_config SET key_word = '拳皇98OL,quanhuang98OL,qh98OL' WHERE pack_name='com.tencent.tmgp.kof98' AND type='1';
UPDATE game_config SET key_word = '超进化物语,chaojinhuawuyu,cjhwy' WHERE pack_name='com.tencent.tmgp.cjhwy,com.tanyu.cjhwy' AND type='1';
UPDATE game_config SET key_word = '英雄杀,yingxiongsha,yxs' WHERE pack_name='com.qqgame.mic' AND type='1';
UPDATE game_config SET key_word = '烈火如歌,liehuoruge,lhrg' WHERE pack_name='com.tencent.tmgp.lhrg,com.aligames.ourpalm.wdqk,com.prefectw.lhrg.zn' AND type='1';
UPDATE game_config SET key_word = '天天酷跑,tiantiankupao,ttkp' WHERE pack_name='com.tencent.tmgp.RunGame' AND type='1';
UPDATE game_config SET key_word = '恋与制作人,lianyuzhizuoren,lyzzr' WHERE pack_name='com.papegames.evol,com.tencent.tmgp.evol' AND type='1';
UPDATE game_config SET key_word = '择天记,zetianji,ztj' WHERE pack_name='com.tencent.tmgp.ztj' AND type='1';
UPDATE game_config SET key_word = '梦幻西游互通版,menghuanxiyouhutongban,mhxyhtb,网易梦幻西游互通版,wangyimenghuanxiyouhutongban,wymhxyhtb,梦幻西游口袋版,menghuanxiyoukoudaiban,mhxykdb' WHERE pack_name='com.netease.mhxyhtb' AND type='1';
UPDATE game_config SET key_word = '劲舞团,劲舞团手游,jinwutuan,jwt,劲舞时代' WHERE pack_name='com.netease.ma59,com.tencent.tmgp.jwt.zqb' AND type='1';
UPDATE game_config SET key_word = '街头篮球,jietoulanqiu,jtlq,街球,jieqiu' WHERE pack_name='com.tencent.freestyle' AND type='1';
UPDATE game_config SET key_word = '热血江湖,rexuejianghu,rxjh' WHERE pack_name='com.tencent.tmgp.rxjhbj,com.longtugame.rxjh,com.duduplay.hk.rxjh' AND type='1';
UPDATE game_config SET key_word = '我的王朝,wodewangchao,wdwc' WHERE pack_name='com.tencent.slgame' AND type='1';
UPDATE game_config SET key_word = '仙境传说RO:守护永恒的爱,Ragnarok Online,xianjingchuanshuoRO:shouhuyonghengdeai,xjcsRO:shyhda' WHERE pack_name='com.xd.ro.roapk' AND type='1';
UPDATE game_config SET key_word = '#COMPASS (TW&JP),#COMPASS (台服),#COMPASS (日服),#COMPASS (TW),#COMPASS (taifu),#COMPASS (tf),戰鬥神意解析系統,战斗天赋解析系统,#コンパス 【戦闘摂理解析システム】' WHERE pack_name='com.nhnpa.cpstw,com.nhnpa.cps' AND type='1';
UPDATE game_config SET key_word = '300大作战,300dazuozhan,300dzz,300英雄' WHERE pack_name='com.jumpw.mobile300' AND type='1';
UPDATE game_config SET key_word = 'Xbox,360' WHERE pack_name='com.microsoft.xboxone.smartglass' AND type='1';
UPDATE game_config SET key_word = '电磁风暴,Afterpulse,diancifengbao,dcfb' WHERE pack_name='com.dle.afterpulse' AND type='1';
UPDATE game_config SET key_word = '爱丽丝机甲,alice gear aegis,ailisijijia,alsjj,アリス・ギア・アイギス' WHERE pack_name='jp.colopl.alice' AND type='1';
UPDATE game_config SET key_word = '妃十三学园(日版),Alternative Girls (JP),feishisanxueyuan(riban),fssxy(rb),オルタナティブガールズ,妃十三學園,替代女友' WHERE pack_name='jp.co.cyberagent.alternajp' AND type='1';
UPDATE game_config SET key_word = '愤怒的小鸟2,Angry Birds 2,fennudexiaoniao2,fndxn2' WHERE pack_name='com.rovio.baba' AND type='1';
UPDATE game_config SET key_word = '愤怒的小鸟:演化,Angry Birds Evolution,fennudexiaoniao:yanhua,fndxn:yh' WHERE pack_name='com.rovio.tnt,com.rovio.tnt.gm' AND type='1';
UPDATE game_config SET key_word = '暗黑魔神,anheimoshen,ahms' WHERE pack_name='com.zhiniu.mfyry' AND type='1';
UPDATE game_config SET key_word = '暗黑战域,anheizhanyu,ahzy,黎明觉醒' WHERE pack_name='com.cq.ahzy' AND type='1';
UPDATE game_config SET key_word = '动物之森:口袋营地,Animal Crossing: Pocket Cam,dongwuzhisen:koudaiyingde,dwzs:kdyd,口袋露营' WHERE pack_name='com.nintendo.zaca' AND type='1';
UPDATE game_config SET key_word = 'Archery King' WHERE pack_name='com.miniclip.archery' AND type='1';
UPDATE game_config SET key_word = '传说对决(亚服),Arena of Valor (AS),chuanshuoduijue(yafu),csdj(yf),王者荣耀海外版,开黑' WHERE pack_name='com.ngame.allstar.eu' AND type='1';
UPDATE game_config SET key_word = '传说对决(欧服),Arena of Valor (EU),chuanshuoduijue(oufu),csdj(of),Strike of Kings:5v5 Arena Game,Arena of Valor: 5v5 Arena Game,王者荣耀欧服,勇气竞技场,开黑' WHERE pack_name='com.ngame.allstar.eu' AND type='1';
UPDATE game_config SET key_word = '传说对决(印尼服),Arena of Valor (ID),chuanshuoduijue(yinnifu),csdj(ynf),王者荣耀,传说对决,英雄联盟,LOL' WHERE pack_name='com.garena.game.kgid' AND type='1';
UPDATE game_config SET key_word = '传说对决(韩服),Arena of Valor (KR),chuanshuoduijue(hanfu),csdj(hf),펜타스톰 for Kakao,五杀风暴,penta storm,开黑' WHERE pack_name='com.netmarble.penta' AND type='1';
UPDATE game_config SET key_word = '传说对决(泰服),Arena of Valor (THA),chuanshuoduijue(taifu),csdj(tf),Garena RoV: Mobile MOBA,王者荣耀泰服,开黑' WHERE pack_name='com.garena.game.kgth' AND type='1';
UPDATE game_config SET key_word = '传说对决(美服),Arena of Valor (US),chuanshuoduijue(meifu),csdj(mf),5v5 Arena Game,傳說對決(US),王者荣耀美服' WHERE pack_name='com.ngame.allstar.eu' AND type='1';
UPDATE game_config SET key_word = '传说对决(越南服),Arena of Valor (VIE),chuanshuoduijue(yuenanfu),csdj(ynf),王者荣耀越南服' WHERE pack_name='com.garena.game.kgvn' AND type='1';
UPDATE game_config SET key_word = '传说对决(体验服),Arena of valor 体验服,chuanshuoduijue(tiyanfu),csdj(tyf),Arena of valor tiyanfu,Arena of valor tyf,传说对决,王者荣耀' WHERE pack_name='com.tencent.ngame.chty' AND type='1';
UPDATE game_config SET key_word = '战争艺术:赤潮,Art of War: Red Tides,zhanzhengyishu:chichao,zzys:cc' WHERE pack_name='com.tencent.tmgp.zzys' AND type='1';
UPDATE game_config SET key_word = '狂野飙车8:极速凌云,Asphalt 8: Airborne,kuangyebiaoche8:jisulingyun,kybc8:jsly' WHERE pack_name='com.gameloft.android.ANMP.GloftA8CN,com.gameloft.android.ANMP.GloftA8HM' AND type='1';
UPDATE game_config SET key_word = '狂野飙车9:传奇,Asphalt 9:Legends,kuangyebiaoche9:chuanqi,kybc9:cq,Asphalt 9: Legends,狂野飙车9竞速传奇,A9' WHERE pack_name='com.gameloft.android.ANMP.GloftA9HM' AND type='1';
UPDATE game_config SET key_word = '狂野飙车:极限越野,Asphalt Xtreme,kuangyebiaoche:jixianyueye,kybc:jxyy' WHERE pack_name='com.gameloft.android.ANMP.GloftMOHM' AND type='1';
UPDATE game_config SET key_word = "刺客信条：本色,Assasin's Creed Identity,cikexintiao：bense,ckxt：bs,cikexintiaobense,Assassin's Creed Identity,AC:Identity,Ubisoft Entertainment,育碧刺客教条：英雄" WHERE pack_name='com.ubisoft.assassinscreed.identity' AND type='1';
UPDATE game_config SET key_word = '幻想神域(台服),Aura Kingdom (TW),huanxiangshenyu(taifu),hxsy(tf),幻想神域,台服,huanxiangshenyu,hxsy,起源女神,qiyuannvshen,qyns' WHERE pack_name='com.xlegend.ff.tw' AND type='1';
UPDATE game_config SET key_word = 'Avakin Life' WHERE pack_name='com.lockwoodpublishing.avakinlife' AND type='1';
UPDATE game_config SET key_word = '碧蓝航线(日服),Azur Lane (JP),bilanhangxian(rifu),blhx(rf),アズールレーン' WHERE pack_name='com.YoStarJP.AzurLane' AND type='1';
UPDATE game_config SET key_word = '碧蓝航线(英文版),Azur Lane (US),bilanhangxian(yingwenban),blhx(ywb),碧藍航線 (Global),国际版' WHERE pack_name='com.YoStarEN.AzurLane' AND type='1';
UPDATE game_config SET key_word = '梦幻少女乐队(日服),BanG Dream (JP),menghuanshaonvledui(rifu),mhsnld(rf),BanG Dream!Girls Band Party!,バンドリ！ ガールズバンドパーティ！' WHERE pack_name='jp.co.craftegg.band' AND type='1';
UPDATE game_config SET key_word = '巴清传,baqingchuan,bqc' WHERE pack_name='com.shandagames.ytx.tuanwan' AND type='1';
UPDATE game_config SET key_word = '战斗海湾,Battle Bay,zhandouhaiwan,zdhw,战舰' WHERE pack_name='com.rovio.battlebay' AND type='1';
UPDATE game_config SET key_word = '战斗女子学园,Battle Girl High School,zhandounvzixueyuan,zdnzxy,戰鬥女子學園,战斗女子学院' WHERE pack_name='tw.sonet.bgh' AND type='1';
UPDATE game_config SET key_word = '球球大作战国际版,Battle of Balls INT,qiuqiudazuozhanguojiban,qqdzzgjb,Battle of Balls' WHERE pack_name='com.ztgame.bobglobal' AND type='1';
UPDATE game_config SET key_word = "战地幸存者:大逃杀,Battleground's Survivor: Battle Royale,zhandexingcunzhe:dataosha,zdxcz:dts,Battleground's Survivor Battle Royale,战地幸存者:皇家战役" WHERE pack_name='com.BatonGames.BattlegroundSurvivor' AND type='1';
UPDATE game_config SET key_word = '崩坏学园2,benghuaixueyuan2,bhxy2' WHERE pack_name='com.miHoYo.game2144.mi,com.miHoYo.HSoDv2,com.miHoYo.HSoDv22144,com.miHoYo.HSoDv2BiliBiliRelease,com.miHoYo.HSoDv2Original' AND type='1';
UPDATE game_config SET key_word = '崩坏学园2(日服),benghuaixueyuan2(rifu),bhxy2(rf),本格横スクロールアクションゲーム' WHERE pack_name='com.miHoYo.HSoDv2JPOriginalEx' AND type='1';
UPDATE game_config SET key_word = '黑色沙漠(台服),Black Desert (TW),heiseshamo(taifu),hssm(tf),Black Desert （TW）,黑色沙漠台服,heiseshamotaifu,hssmtf,黑色沙漠 MOBILE,black desert,heiseshamo' WHERE pack_name='com.pearlabyss.blackdesertm.tw2' AND type='1';
UPDATE game_config SET key_word = '黑色沙漠(韩服),Black Desert(KR),heiseshamo(hanfu),hssm(hf),黑色沙漠韩服,heiseshamohanfu,hssmhf,黑色沙漠,黑色沙漠手游,heiseshamo,hssm,검은사막 모바일,blackdesertm,黑沙' WHERE pack_name='com.pearlabyss.blackdesertm' AND type='1';
UPDATE game_config SET key_word = '黑色幸存,Black Survival,heisexingcun,hsxc,블랙서바이벌,ブラサバ' WHERE pack_name='com.archbears.bs' AND type='1';
UPDATE game_config SET key_word = '苍翼之刃(日服),BLAZBLUE RR,cangyizhiren(rifu),cyzr(rf),BLAZBLUE REVOLUTION REBURNING,苍翼默示录(JP)' WHERE pack_name='com.actgames.bbrr.jp' AND type='1';
UPDATE game_config SET key_word = '苍翼之刃(国际版),Blazblue RR,cangyizhiren(guojiban),cyzr(gjb),BLAZBLUE REVOLUTION REBURNING,苍翼默示录,CYMSL' WHERE pack_name='com.actgames.bbrr.sgp' AND type='1';
UPDATE game_config SET key_word = '闪电部队:策略对决,Blitz Brigade,shandianbudui:celveduijue,sdbd:cldj' WHERE pack_name='com.gameloft.android.ANMP.GloftTAHM' AND type='1';
UPDATE game_config SET key_word = '閃電突擊隊,Blitz Brigade,shandiantujidui,sdtjd,闪电突击队,闪电部队' WHERE pack_name='com.gameloft.android.ANMP.GloftINHM' AND type='1';
UPDATE game_config SET key_word = '海岛奇兵,Boom Beach,haidaoqibing,hdqb,boom beach' WHERE pack_name='com.supercell.boombeach' AND type='1';
UPDATE game_config SET key_word = '泡泡趴,Bubble Popa,paopaopa,ppp,网易,wangyi,wy' WHERE pack_name='com.tencent.tmgp.ppp.djly,com.netease.ppp' AND type='1';
UPDATE game_config SET key_word = '不良人2,buliangren2,blr2' WHERE pack_name='com.tencent.tmgp.yunchang.buliangren' AND type='1';
UPDATE game_config SET key_word = '子弹力量,Bullet Force,zidanliliang,zdll,外服Bullet Force,cf,FPS' WHERE pack_name='com.blayzegames.iosfps' AND type='1';
UPDATE game_config SET key_word = '文豪与炼金术师,Bungo to Alchemist,wenhaoyulianjinshushi,whyljss,文豪與鍊金術士' WHERE pack_name='com.dmmgames.bunal,com.dmm.games.bunal' AND type='1';
UPDATE game_config SET key_word = '足球小将翼:梦之队伍(国际版),Captain Tsubasa:Dream Team,zuqiuxiaojiangyi:mengzhiduiwu(guojiban),zqxjy:mzdw(gjb)' WHERE pack_name='com.klab.captain283.global' AND type='1';
UPDATE game_config SET key_word = '驾校模拟,Car Driving School Simulator,jiaxiaomoni,jxmn' WHERE pack_name='com.boombitgames.DrivingSchoolParking' AND type='1';
UPDATE game_config SET key_word = '保卫萝卜1,Carrot Fantasy 1,baoweiluobo1,bwlb1' WHERE pack_name='com.carrot.carrotfantasy' AND type='1';
UPDATE game_config SET key_word = '超杀默示录,chaoshamoshilu,csmsl' WHERE pack_name='com.tencent.tmgp.csmsl,com.kr.hero.csmsl.ewan' AND type='1';
UPDATE game_config SET key_word = '冲啊三国,chongasanguo,casg' WHERE pack_name='com.muyou.jingqi.casg' AND type='1';
UPDATE game_config SET key_word = '虫虫大作战,chongchongdazuozhan,ccdzz' WHERE pack_name='com.jingmo.ccdzz,com.tencent.tmgp.ccdzzkp' AND type='1';
UPDATE game_config SET key_word = '冲顶大会,chongdingdahui,cddh,问答,答题' WHERE pack_name='com.chongdingdahui.app' AND type='1';
UPDATE game_config SET key_word = '时空魔法,CHRONO MA:GIA,shikongmofa,skmf,クロノマギア' WHERE pack_name='jp.gungho.cmg' AND type='1';
UPDATE game_config SET key_word = '创元战纪,chuangyuanzhanji,cyzj' WHERE pack_name='com.yinhu.sdk.fzjy.pj' AND type='1';
UPDATE game_config SET key_word = '创造与魔法,chuangzaoyumofa,czymf' WHERE pack_name='com.hero.sm.android.hero,com.tencent.tmgp.sm' AND type='1';
UPDATE game_config SET key_word = '传奇世界3D,chuanqishijie3D,cqsj3D' WHERE pack_name='com.tencent.woool3d' AND type='1';
UPDATE game_config SET key_word = '传奇世界手游,chuanqishijieshouyou,cqsjsy,The World Of Legend' WHERE pack_name='com.tencent.cqsj' AND type='1';
UPDATE game_config SET key_word = '传说对决体验服(越南),chuanshuoduijuetiyanfu(yuenan),csdjtyf(yn),Garena Liên Quân Mobile,傳說對決體驗服' WHERE pack_name='com.garena.game.kgvntest' AND type='1';
UPDATE game_config SET key_word = '炫动城市,City Mania,xuandongchengshi,xdcs,gameloft,模拟城市,monichengshi' WHERE pack_name='com.gameloft.citybuilder,com.gameloft.android.ANMP.GloftCMHM' AND type='1';
UPDATE game_config SET key_word = '次元大作战,ciyuandazuozhan,cydzz' WHERE pack_name='cn.emagroup.kom.Tombird,com.tencent.tmgp.mbzw2' AND type='1';
UPDATE game_config SET key_word = '疯狂战争,Crazy War,fengkuangzhanzheng,fkzz' WHERE pack_name='com.CG.FPS' AND type='1';
UPDATE game_config SET key_word = 'Destruction(亚服),Creative Destruction (AS),Creative Destruction(yafu),Creative Destruction(yf),Creative Destruction,堡垒前线(海外版),baoleiqianxian(haiwaiban),blqx(hwb),启明星之谷,qimingxingzhigu,qmxzg' WHERE pack_name='com.titan.cd.gb	Creative' AND type='1';
UPDATE game_config SET key_word = '全民枪战,Crisis Action,quanminqiangzhan,qmqz' WHERE pack_name='com.crisisfire.cmge,com.tencent.tmgp.qmqzhero' AND type='1';
UPDATE game_config SET key_word = '穿越火线(韩服),CrossFire (KR),chuanyuehuoxian(hanfu),cyhx(hf),탄: 끝없는 전장,弹:无限战场,彈:无尽战场,FPS,CF' WHERE pack_name='com.stove.cfm.google' AND type='1';
UPDATE game_config SET key_word = '穿越火线(越南服),CrossFire (VIE),chuanyuehuoxian(yuenanfu),cyhx(ynf),Crossfire:Legends,CF' WHERE pack_name='com.gs5.cfm' AND type='1';
UPDATE game_config SET key_word = '武裝菁英,CrossFire TW,wuzhuangjingying,wzjy,武装精英,CF,穿越火线台服,Garena' WHERE pack_name='com.garena.game.botw' AND type='1';
UPDATE game_config SET key_word = '穿越火线(泰服),CrossFire:Legends,chuanyuehuoxian(taifu),cyhx(tf)' WHERE pack_name='com.gs5.cfm.th' AND type='1';
UPDATE game_config SET key_word = '克鲁赛德战记,Crusaders Quest,kelusaidezhanji,klsdzj,克魯賽德戰記,外服' WHERE pack_name='com.tencent.tmgp.klsdzj,com.tencent.tmgp.klsdxsdz,com.nhnst.SKCQCN,com.toastgame.hsp.otakuchannel.LaunchActivity,com.nhnst.skcqcn.xindong' AND type='1';
UPDATE game_config SET key_word = '大话苍穹,dahuacangqiong,dhcq' WHERE pack_name='com.slgame.dhcq.silang' AND type='1';
UPDATE game_config SET key_word = '大皇帝OL,dahuangdiOL,dhdOL' WHERE pack_name='com.tencent.tmgp.dhd,com.uuzu.king.yz' AND type='1';
UPDATE game_config SET key_word = '大话西游热血版,dahuaxiyourexueban,dhxyrxb,网易大话西游热血版,wangyidahuaxiyourexueban,wydhxyrxb' WHERE pack_name='com.netease.dhxyrxb,com.tencent.tmgp.yinhan.dhxyrxb' AND type='1';
UPDATE game_config SET key_word = '代号:Rider,daihao:Rider,dh:Rider,wangyi,网易,wy' WHERE pack_name='com.netease.pm04' AND type='1';
UPDATE game_config SET key_word = '代号英雄,daihaoyingxiong,dhyx' WHERE pack_name='com.yingxiong.gw.Android.hero,com.yingxiong.heroo.nearme.gamecenter' AND type='1';
UPDATE game_config SET key_word = '弹弹岛2,dandandao2,ddd2' WHERE pack_name='com.wyd.hero.dandandao.hero,com.tencent.tmgp.DDD2' AND type='1';
UPDATE game_config SET key_word = '弹弹堂,dandantang,ddt' WHERE pack_name='com.tencent.tmgp.ddtank' AND type='1';
UPDATE game_config SET key_word = '弹弹堂S,dandantangS,ddtS' WHERE pack_name='com.tencent.tmgp.ddtankghw,com.ddtankfcb.marwee' AND type='1';
UPDATE game_config SET key_word = '刀锋无双2,daofengwushuang2,dfws2' WHERE pack_name='com.ezfun.dfws2.sjoys' AND type='1';
UPDATE game_config SET key_word = '刀剑兵器谱,daojianbingqipu,djbqp' WHERE pack_name='com.tencent.tmgp.bqp,net.aligames.pixelgame.bqp' AND type='1';
UPDATE game_config SET key_word = '刀剑乱舞OL,daojianluanwuOL,djlwOL' WHERE pack_name='com.tencent.tmgp.djlwol,com.youzu.djlw' AND type='1';
UPDATE game_config SET key_word = '刀剑萌侠,daojianmengxia,djmx' WHERE pack_name='com.chuangyunet.djmx.hncy' AND type='1';
UPDATE game_config SET key_word = '刀剑侠,daojianxia,djx' WHERE pack_name='com.sq.djx.papa' AND type='1';
UPDATE game_config SET key_word = '刀塔西游,daotaxiyou,dtxy' WHERE pack_name='com.tnyoo.dota,com.tencent.tmgp.dotaxiyou.tnyoo.android,com.dotaxiyouxx.cn' AND type='1';
UPDATE game_config SET key_word = '大掌门2,dazhangmen2,dzm2,dazhangmen2wenziban,dzm2wzb' WHERE pack_name='com.playcrab.dazhangmen2.uwan' AND type='1';
UPDATE game_config SET key_word = '暗无天日,Dead Rivals,anwutianri,awtr,unreleased,末日危機-屍戰mmo' WHERE pack_name='com.gameloft.android.ANMP.GloftWOHM' AND type='1';
UPDATE game_config SET key_word = '死亡扳机2,Dead Trigger 2,siwangbanji2,swbj2' WHERE pack_name='com.madfingergames.deadtrigger2' AND type='1';
UPDATE game_config SET key_word = '地牢猎手5,delaolieshou5,dlls5,DungeonHunter5' WHERE pack_name='com.gameloft.android.ANMP.Gloft5DHM,com.tencent.tmgp.android.ANMP.GloftG5EG' AND type='1';
UPDATE game_config SET key_word = '天命之子(日服),Destiny Child (JP),tianmingzhizi(rifu),tmzz(rf),デスティニーチャイルド' WHERE pack_name='com.stairs.destinychild' AND type='1';
UPDATE game_config SET key_word = '地下城堡2:暗黑觉醒,dexiachengbao2:anheijuexing,dxcb2:ahjx' WHERE pack_name='com.taojin.dungeon2,com.tencent.tmgp.dungeon22' AND type='1';
UPDATE game_config SET key_word = '独裁者:现身,Dictator: Emergence,ducaizhe:xianshen,dcz:xs,Dictator:Emergence,独裁者：现身,ducaizhe：xianshen,dcz：xs' WHERE pack_name='com.tigrido.dictator.emergence' AND type='1';
UPDATE game_config SET key_word = '数码宝贝 ReArise,Digimon ReArise,shumabaobei ReArise,smbb ReArise,数码暴龙,デジモンリアライズ,デジライズ' WHERE pack_name='com.bandainamcoent.digimon_rearise' AND type='1';
UPDATE game_config SET key_word = 'DMM Games' WHERE pack_name='com.dmm.app.store' AND type='1';
UPDATE game_config SET key_word = '阿拉德之怒,DNL,aladezhinu,aldzn,DNF,地下城盟约' WHERE pack_name='com.hegu.dnl.mg' AND type='1';
UPDATE game_config SET key_word = '少女前线(日服),Dolls Frontline,shaonvqianxian(rifu),snqx(rf),DollsFrontline,少女前线日服,ドールズフロントライン,少女前線' WHERE pack_name='com.sunborn.girlsfrontline.jp' AND type='1';
UPDATE game_config SET key_word = "饥荒:口袋版,Don't Starve: Pocket Edition,jihuang:koudaiban,jh:kdb" WHERE pack_name='com.kleientertainment.dontstarvepocket,com.kleientertainment.doNotStarvePocket' AND type='1';
UPDATE game_config SET key_word = "饥荒:海难,Don't Starve:Shipwrecked,jihuang:hainan,jh:hn" WHERE pack_name='com.kleientertainment.doNotStarveShipwrecked,apps-com.kleientertainment.doNotStarveShipwrecked' AND type='1';
UPDATE game_config SET key_word = '东京战纪,dongjingzhanji,djzj,Tokyo Ghoul,东京喰种,东京食尸鬼,dongjingcanzhong,djcz,dongjingshishigui,djssg' WHERE pack_name='com.tencent.tmgp.ghoul,com.digitalsky.ghoul.cn' AND type='1';
UPDATE game_config SET key_word = '七龙珠激战传说,DRAGON BALL LEGENDS,qilongzhujizhanchuanshuo,qlzjzcs,七龍珠激戰傳說,qilongzhu jizhanchuanshuo,qlz jzcs,DBLEGENDS' WHERE pack_name='com.bandainamcoent.dblegends_ww,com.bandainamcoent.dblegends_jp' AND type='1';
UPDATE game_config SET key_word = '七龙珠爆裂激战(台服),DragonBall Z:Dokkan Battle (TW),qilongzhubaoliejizhan(taifu),qlzbljz(tf)' WHERE pack_name='com.bandainamcogames.dbzdokkanww' AND type='1';
UPDATE game_config SET key_word = '勇者斗恶龙:宿敌,DragonQuest:Rivals,yongzhedouelong:sudi,yzdel:sd,ドラゴンクエストライバルズ,DQR' WHERE pack_name='com.square_enix.android_googleplay.DQRivals' AND type='1';
UPDATE game_config SET key_word = '野生之地:杜兰戈,Durango: Wild Lands,yeshengzhide:dulange,yszd:dlg' WHERE pack_name='com.nexon.durango' AND type='1';
UPDATE game_config SET key_word = 'D×2 真・女神转生:解放,D×2 zhen・nvshenzhuansheng:jiefang,D×2 z・nszs:jf' WHERE pack_name='com.sega.d2megaten.zh_hant' AND type='1';
UPDATE game_config SET key_word = '第七史诗,Epic 7,diqishishi,dqss,epic 7,에픽세븐' WHERE pack_name='com.stove.epic7.google' AND type='1';
UPDATE game_config SET key_word = '永恒的卡牌游戏,Eternal Card Game,yonghengdekapaiyouxi,yhdkpyx,yongheng,kapaiyouxi,tcg,炉石,eternalcardgame' WHERE pack_name='com.direwolfdigital.Phoenix' AND type='1';
UPDATE game_config SET key_word = '无尽神域,Eternal Realm,wujinshenyu,wjsy,网易,wangyi,wy' WHERE pack_name='com.netease.wjsy,com.tencent.tmgp.wjsy' AND type='1';
UPDATE game_config SET key_word = '僵尸启示,Experiment Z,jiangshiqishi,jsqs,试验Z' WHERE pack_name='com.cyclopsgames.experimentz' AND type='1';
UPDATE game_config SET key_word = '反斗海战,fandouhaizhan,fdhz' WHERE pack_name='com.netease.g84' AND type='1';
UPDATE game_config SET key_word = '反斗联盟,fandoulianmeng,fdlm' WHERE pack_name='com.tencent.tmgp.gunnergo,com.gunnergofinal.kunpo.lenovo' AND type='1';
UPDATE game_config SET key_word = '放开那三国,fangkainasanguo,fknsg' WHERE pack_name='com.sincetimes.fknsg' AND type='1';
UPDATE game_config SET key_word = '翻滚球球,fangunqiuqiu,fgqq' WHERE pack_name='com.jingmo.ball3d,com.sy4399.ball3d.vivo' AND type='1';
UPDATE game_config SET key_word = '放学别跑,fangxuebiepao,fxbp' WHERE pack_name='com.ilongyuan.fxbp.ly,com.tencent.tmgp.fxbp' AND type='1';
UPDATE game_config SET key_word = '放逐游戏,fangzhuyouxi,fzyx,ExileGame,放逐游戏—大逃杀,fangzhuyouxi—dataosha,fzyx—dts,大吉大利今晚吃鸡,ShooterGame,战地之王' WHERE pack_name='com.yuejunzhang.home' AND type='1';
UPDATE game_config SET key_word = '饭局狼人杀,fanjulangrensha,fjlrs,狼人杀,langrensha,lrs' WHERE pack_name='com.mewe.party,com.mewe.wolf' AND type='1';
UPDATE game_config SET key_word = '凡仙,fanxian,fx' WHERE pack_name='com.fy.twfy.xiyou' AND type='1';
UPDATE game_config SET key_word = '黄金弹头,Fatal Raid,huangjindantou,hjdt,虛幻戰場,gun fire' WHERE pack_name='com.selvas.fr' AND type='1';
UPDATE game_config SET key_word = 'Fate/GO(美服),Fate/GO (US),Fate/GO(meifu),Fate/GO(mf),Fate/Grand Order (English),Fate_GO,FGOMF' WHERE pack_name='com.aniplex.fategrandorder.en' AND type='1';
UPDATE game_config SET key_word = '疯狂贪吃蛇,fengkuangtanchishe,fktcs,贪吃蛇' WHERE pack_name='com.tencent.tmgp.snk' AND type='1';
UPDATE game_config SET key_word = '风之纪元,fengzhijiyuan,fzjy' WHERE pack_name='com.yinhu.sdk.fzjy.pj' AND type='1';
UPDATE game_config SET key_word = 'Soccer,FIFA 16' WHERE pack_name='com.ea.gp.fifaworld	FIFA 16' AND type='1';
UPDATE game_config SET key_word = 'FIFA足球(国际版),FIFA Soccer,FIFAzuqiu(guojiban),FIFAzq(gjb),FIFA World Cup™,FIFA Mobile,fifamobile' WHERE pack_name='com.ea.gp.fifamobile' AND type='1';
UPDATE game_config SET key_word = '交锋联盟,Fight League,jiaofenglianmeng,jflm,交鋒聯盟' WHERE pack_name='com.xflag.fightleagueGL' AND type='1';
UPDATE game_config SET key_word = '最终幻想:觉醒,Final Fantasy Awakening,zuizhonghuanxiang:juexing,zzhx:jx,FINAL FANTASY最終幻想：覺醒' WHERE pack_name='tw.com.iwplay.ff' AND type='1';
UPDATE game_config SET key_word = '最终幻想:勇气Exvius,Final Fantasy Brave Exvius,zuizhonghuanxiang:yongqiExvius,zzhx:yqExvius,FF EXVIUS,最终幻想 勇气启示录,zuizhonghuanxiang yongqiqishilu,zzhx yqqsl' WHERE pack_name='com.square-enix.ffbeww,com.square_enix.android_googleplay.FFBEWW' AND type='1';
UPDATE game_config SET key_word = '火焰纹章:英雄,Fire Emblem Heroes,huoyanwenzhang:yingxiong,hywz:yx,火焰纹章：英雄,huoyanwenzhang：yingxiong,hywz：yx,fe,fire emblem heroes,日服外服' WHERE pack_name='com.nintendo.zaba' AND type='1';
UPDATE game_config SET key_word = '前锋突袭,Forward Assault,qianfengtuxi,qftx,FWD' WHERE pack_name='com.blayzegames.newfps' AND type='1';
UPDATE game_config SET key_word = 'Critical Ops,fps,射击,cs,cf,cops,c-ops,关键行动,guanjianxingdong,gjxd' WHERE pack_name='com.criticalforceentertainment.criticalops' AND type='1';
UPDATE game_config SET key_word = 'Free Fire,Free Fire - 我要活下去,Battlegrounds,大逃杀,自由开火,自由射击' WHERE pack_name='com.dts.freefireth' AND type='1';
UPDATE game_config SET key_word = '孤胆车神:新奥尔良,Gangstar: New Orleans,gudancheshen:xinaoerliang,gdcs:xael,Gangstar：New Orleans,Gangstar New Orleans: Action Open World Game' WHERE pack_name='com.gameloft.android.ANMP.GloftOLHM' AND type='1';
UPDATE game_config SET key_word = '传说对决(新加坡服),Garena AOV (SG),chuanshuoduijue(xinjiapofu),csdj(xjpf),Garena AOV - Arena of Valor (PH/MY/SG)' WHERE pack_name='com.garena.game.kgsam' AND type='1';
UPDATE game_config SET key_word = 'Garena移动版,Garena Mobile,Garenayidongban,Garenaydb' WHERE pack_name='com.garena.gas' AND type='1';
UPDATE game_config SET key_word = '宝石战争,Gems of War,baoshizhanzheng,bszz' WHERE pack_name='air.com.and.games505.gemsofwar' AND type='1';
UPDATE game_config SET key_word = '少女与战车 集结！大家的战车道！！,Girls Und Panzer: Atsumare! Mina no Senshado!!,  shaonvyuzhanche jijie！dajiadezhanchedao！！,  snyzc jj！djdzcd！！,少女与战车 集结！大家的战车道！！,shaonvyuzhanche jijie！dajiadezhanchedao！！,snyzc jj！djdzcd！！,ガルみん,少女与战车,ガールズ＆パンツァー あつまれ！みんなの戦車道！！' WHERE pack_name='com.bandainamcoent.garupan' AND type='1';
UPDATE game_config SET key_word = '我的学妹不可能这么萌,Girls X Battle,wodexuemeibukenengzhememeng,wdxmbknzmm' WHERE pack_name='com.game168.acdemygo,com.game168.moemoegirls,com.game168.moemoegirlsobt' AND type='1';
UPDATE game_config SET key_word = "少女前线(韩服),Girls' Frontline (KR),shaonvqianxian(hanfu),snqx(hf),少女前線(KR)" WHERE pack_name='kr.txwy.and.snqx' AND type='1';
UPDATE game_config SET key_word = "少女前线(台服),Girls' Frontline (TW),shaonvqianxian(taifu),snqx(tf)" WHERE pack_name='tw.txwy.and.snqx' AND type='1';
UPDATE game_config SET key_word = "少女前线(美服),Girls' Frontline (US),shaonvqianxian(meifu),snqx(mf)" WHERE pack_name='com.sunborn.girlsfrontline.us,com.sunborn.girlsfrontline.en' AND type='1';
UPDATE game_config SET key_word = '噬神者OL,God Eater Online,shishenzheOL,sszOL,弒神者OL,GOD EATER ONLINE,GE Online' WHERE pack_name='jp.co.bandainamcoent.BNEI0282,com.bandainamcoent.godeateronline' AND type='1';
UPDATE game_config SET key_word = '功夫熊猫3,gongfuxiongmao3,gfxm3,网易功夫熊猫3,wangyigongfuxiongmao3,wygfxm3' WHERE pack_name='com.tencent.tmgp.hqfy,com.netease.gfxm3' AND type='1';
UPDATE game_config SET key_word = '弓箭手大作战,gongjianshoudazuozhan,gjsdzz,arrow.io,gongjianshou' WHERE pack_name='com.cmcm.arrowio' AND type='1';
UPDATE game_config SET key_word = '碧蓝幻想(日服),Granblue Fantasy (JP),bilanhuanxiang(rifu),blhx(rf),グランブルーファンタジー,granblue fantasy' WHERE pack_name='jp.mbga.a12016007.lite' AND type='1';
UPDATE game_config SET key_word = '像素大逃杀,Grand Battle Royale,xiangsudataosha,xsdts,大逃杀' WHERE pack_name='com.onetongames.kingofthehill' AND type='1';
UPDATE game_config SET key_word = '侠盗猎车手:圣安地列斯,GTA:SA,xiadaoliecheshou:shengandeliesi,xdlcs:sadls,GTA5' WHERE pack_name='com.rockstargames.gtasa' AND type='1';
UPDATE game_config SET key_word = '乖离性百万亚瑟王,guailixingbaiwanyasewang,glxbwysw,网易乖离性百万亚瑟王,wangyiguailixingbaiwanyasewang,wyglxbwysw,乖离性MA' WHERE pack_name='com.tencent.tmgp.glxbwysw,com.netease.ma43.lenovo,com.netease.ma43,com.netease.ma' AND type='1';
UPDATE game_config SET key_word = '怪兽大作战,guaishoudazuozhan,gsdzz' WHERE pack_name='com.jingmo.gsdzz,com.tencent.tmgp.gsdzz' AND type='1';
UPDATE game_config SET key_word = '挂机三国志,guajisanguozhi,gjsgz' WHERE pack_name='com.yinhu.sdk.gjsgz.pj' AND type='1';
UPDATE game_config SET key_word = '光荣使命,guangrongshiming,grsm,吃鸡大逃杀' WHERE pack_name='com.tencent.cldts' AND type='1';
UPDATE game_config SET key_word = '航海王激战,hanghaiwangjizhan,hhwjz,海贼王' WHERE pack_name='com.tencent.tmgp.onepiecefighting' AND type='1';
UPDATE game_config SET key_word = '哈利波特,Harry Potter,halibote,hlbt,哈利波特：霍格沃茨的秘密,halibote：huogewocidemimi,hlbt：hgwcdmm,Harry Potter: Hogwarts Mystery' WHERE pack_name='com.tinyco.potter' AND type='1';
UPDATE game_config SET key_word = '卡通农场,Hay Day,katongnongchang,ktnc' WHERE pack_name='com.supercell.hayday' AND type='1';
UPDATE game_config SET key_word = '黑衣剑士,heiyijianshi,hyjs,刀剑神域' WHERE pack_name='com.tencent.tmgp.yunchang.djsy' AND type='1';
UPDATE game_config SET key_word = '英雄血战,Heroes Arena,yingxiongxuezhan,yxxz,moba' WHERE pack_name='com.ucool.heroesarena' AND type='1';
UPDATE game_config SET key_word = '英魂之刃(国际服),Heroes Evolved (INT),yinghunzhiren(guojifu),yhzr(gjf),Heroes Evolved,开黑,MOBA,英魂之刃,yinghunzhiren,yhzr' WHERE pack_name='com.rsg.heroesevolved' AND type='1';
UPDATE game_config SET key_word = '混沌与秩序之英雄战歌,Heroes of Order & Chaos,hundunyuzhixuzhiyingxiongzhange,hdyzxzyxzg,Heroes OC' WHERE pack_name='com.gameloft.heroesoc,com.gameloft.android.ANMP.GloftHOHM' AND type='1';
UPDATE game_config SET key_word = '躲猫猫大作战(国际版),Hide.io (INT),duomaomaodazuozhan(guojiban),dmmdzz(gjb),躲猫猫大作战,duomaomaodazuozhan,dmmdzz' WHERE pack_name='com.igenesoft.hide' AND type='1';
UPDATE game_config SET key_word = '登山赛车2,Hill Climb Racing 2,dengshansaiche2,dssc2' WHERE pack_name='com.fingersoft.hcr2.cn.tencent,com.mygamez.hcr2.vivo,com.fingersoft.hcr2.cn.noncmcc' AND type='1';
UPDATE game_config SET key_word = '我守护的一切,HIT,woshouhudeyiqie,wshdyq,hit' WHERE pack_name='com.netease.hit,com.tencent.tmgp.hit' AND type='1';
UPDATE game_config SET key_word = 'HIT(日服),HIT (JP),HIT(rifu),HIT(rf),HIT - ヒット,英雄之戰' WHERE pack_name='com.nexon.hit.japan' AND type='1';
UPDATE game_config SET key_word = '杀手:狙击,Hitman Sniper,shashou:juji,ss:jj,代号47:狙击,daihao47:juji,dh47:jj,fps,射击' WHERE pack_name='com.squareenixmontreal.hitmansniperandroid.gld,com.squareenixmontreal.hitmansniper,com.squareenixmontreal.hitmansniperandroid' AND type='1';
UPDATE game_config SET key_word = '黑洞大作战,Hole.io,heidongdazuozhan,hddzz' WHERE pack_name='io.voodoo.holeio' AND type='1';
UPDATE game_config SET key_word = '洪荒修真,honghuangxiuzhen,hhxz' WHERE pack_name='com.yagame.qytx.hhxz' AND type='1';
UPDATE game_config SET key_word = '崩壊3rd(日服),Honkai Impact 3 (JP),benghuai3rd(rifu),bh3rd(rf),崩坏3' WHERE pack_name='com.miHoYo.bh3rdJP' AND type='1';
UPDATE game_config SET key_word = '崩坏3(东南亚服),Honkai Impact 3 (SEA),benghuai3(dongnanyafu),bh3(dnyf)' WHERE pack_name='com.miHoYo.bh3oversea' AND type='1';
UPDATE game_config SET key_word = '欢乐狼人杀,huanlelangrensha,hllrs' WHERE pack_name='com.duowan.makefriends' AND type='1';
UPDATE game_config SET key_word = '欢乐球吃球,huanleqiuchiqiu,hlqcq' WHERE pack_name='com.tencent.tmgp.hlxq' AND type='1';
UPDATE game_config SET key_word = '花千骨,huaqiangu,hqg' WHERE pack_name='com.tencent.tmgp.sm.hqg,com.onektower.tgame' AND type='1';
UPDATE game_config SET key_word = '胡莱三国2,hulaisanguo2,hlsg2' WHERE pack_name='com.tencent.tmgp.hlsg2,com.hoolai.sanguo2' AND type='1';
UPDATE game_config SET key_word = '火炬之光,huojuzhiguang,hjzg,torch light' WHERE pack_name='com.tencent.tmgp.torchlight,com.wanmei.torchlight.ios.laohu,com.wanmei.torchlight.android' AND type='1';
UPDATE game_config SET key_word = '火线精英,huoxianjingying,hxjy' WHERE pack_name='com.tencent.tmgp.hxjysy,com.sy4399.hxjy' AND type='1';
UPDATE game_config SET key_word = '第五人格(亚服),Identity V (AS),diwurenge(yafu),dwrg(yf),网易,wangyi,wy,黎明杀机,杀鸡,海外服' WHERE pack_name='com.netease.idv.googleplay,com.netease.idv_tw.googleplay' AND type='1';
UPDATE game_config SET key_word = '第五人格(欧美服),Identity V (EU-NA),diwurenge(oumeifu),dwrg(omf),网易,wangyi,wy,黎明杀机,杀鸡' WHERE pack_name='com.netease.idv_tw.googleplay,com.netease.idv.googleplay' AND type='1';
UPDATE game_config SET key_word = '偶像大师 灰姑娘女孩 星光舞台,Idol Master,ouxiangdashi huiguniangnvhai xingguangwutai,oxds hgnnh xgwt,アイドルマスター シンデレラガールズ スターライトステージ,idol master' WHERE pack_name='jp.co.bandainamcoent.BNEI0242' AND type='1';
UPDATE game_config SET key_word = '无尽行动,Infinity Ops,wujinxingdong,wjxd,命运之战,mingyunzhizhan,myzz' WHERE pack_name='com.gamedevltd.destinywarfare' AND type='1';
UPDATE game_config SET key_word = '不义联盟2,Injustice 2,buyilianmeng2,bylm2,不义联盟2手游' WHERE pack_name='com.wb.goog.injustice.brawler2017' AND type='1';
UPDATE game_config SET key_word = '加勒比海盗:启航,jialeibihaidao:qihang,jlbhd:qh' WHERE pack_name='com.tipcat.uuuo.jlbhd,com.shyxjlb.haidaoqh' AND type='1';
UPDATE game_config SET key_word = '江湖大夢,jianghudameng,jhdm' WHERE pack_name='com.gm99.clx' AND type='1';
UPDATE game_config SET key_word = '剑侠情缘2,jianxiaqingyuan2,jxqy2,仙侠情缘2,xianxiaqingyuan2,xxqy2' WHERE pack_name='com.tencent.tmgp.jxqy' AND type='1';
UPDATE game_config SET key_word = '剑侠世界,jianxiashijie,jxsj' WHERE pack_name='com.tencent.tmgp.wali.jianxiashijie3D,com.wali.jianxiashijie3D' AND type='1';
UPDATE game_config SET key_word = '剑与荣耀,jianyurongyao,jyry' WHERE pack_name='com.android.ninefun.mmo.yueyou.guopan' AND type='1';
UPDATE game_config SET key_word = '街机三国,jiejisanguo,jjsg' WHERE pack_name='com.tencent.tmgp.ztgame.j3' AND type='1';
UPDATE game_config SET key_word = '街篮,jielan,jl,街头篮球,jietoulanqiu,街球,jieqiu' WHERE pack_name='com.ztgame.jl,com.ztgame.jielan' AND type='1';
UPDATE game_config SET key_word = '街篮(台服),jielan(taifu),jl(tf),街頭籃球,街头篮球,jietoulanqiu,jtlq' WHERE pack_name='com.herogame.gplay.streetballtw' AND type='1';
UPDATE game_config SET key_word = '街篮高手,jielangaoshou,jlgs' WHERE pack_name='com.xtw.jlgs' AND type='1';
UPDATE game_config SET key_word = '节奏大师,jiezoudashi,jzds' WHERE pack_name='com.tencent.game.rhythmmaster' AND type='1';
UPDATE game_config SET key_word = '姬魔恋战纪,jimolianzhanji,jmlzj' WHERE pack_name='com.tencent.tmgp.jmlzj,com.yile.game.jmlzj' AND type='1';
UPDATE game_config SET key_word = '京刀那由多,jingdaonayouduo,jdnyd,京刀のナユタ,jingdaoのナユタ,jdのナユタ' WHERE pack_name='jp.co.ponos.jaguar' AND type='1';
UPDATE game_config SET key_word = '九阴真经3D,jiuyinzhenjing3D,jyzj3D' WHERE pack_name='com.tencent.tmgp.jyzj3dx,com.aicombo.ol9yin3d,com.snailgame.jyzjyd.snail' AND type='1';
UPDATE game_config SET key_word = '九州天空城3D,jiuzhoutiankongcheng3D,jztkc3D' WHERE pack_name='com.zulong.jztkc.zulong,com.tencent.tmgp.jz' AND type='1';
UPDATE game_config SET key_word = '决斗之城,juedouzhicheng,jdzc,游戏王' WHERE pack_name='com.tencent.tmgp.tyjdzc' AND type='1';
UPDATE game_config SET key_word = '决战昆仑,juezhankunlun,jzkl' WHERE pack_name='com.windplay.tl.csj.xiaoyi' AND type='1';
UPDATE game_config SET key_word = '君临天下,junlintianxia,jltx' WHERE pack_name='com.tencent.tmgp.u9time.jltx' AND type='1';
UPDATE game_config SET key_word = '卡片怪兽,kapianguaishou,kpgs' WHERE pack_name='com.tencent.cardmonster,com.mu77.cm' AND type='1';
UPDATE game_config SET key_word = '兽娘动物园:展览区,Kemono Friends: Pavilion,shouniangdongwuyuan:zhanlanqu,sndwy:zlq,けものフレンズぱびりおん,動物朋友PAVILION' WHERE pack_name='com.bushiroad.kemofure' AND type='1';
UPDATE game_config SET key_word = '王之袭击,King’s Raid,wangzhixiji,wzxj,kings raid' WHERE pack_name='com.vespainteractive.KingsRaid,apps-com.vespainteractive.KingsRaid' AND type='1';
UPDATE game_config SET key_word = '闪耀幻想曲,Kirara Fantasia,shanyaohuanxiangqu,syhxq,きららファンタジア,芳文社,琪拉拉幻想曲' WHERE pack_name='com.aniplex.kirarafantasia' AND type='1';
UPDATE game_config SET key_word = '荒野行动(日服),Knives Out (JP),huangyexingdong(rifu),hyxd(rf),荒野行動-スマホ版バトロワ,网易,wangyi,wy,吃鸡,chiji,cj' WHERE pack_name='com.netease.ko,com.netease.hyxd,com.tencent.tmgp.hyxddjly,com.netease.hyxdtw' AND type='1';
UPDATE game_config SET key_word = '拳皇:全明星,KOF ALLSTAR,quanhuang:quanmingxing,qh:qmx,THE KING OF FIGHTERS ALLSTAR' WHERE pack_name='com.netmarble.kof' AND type='1';
UPDATE game_config SET key_word = '快斩狂刀,kuaizhankuangdao,kzkd' WHERE pack_name='com.mfjfghjytyd.ikfgdsxetgdg,com.xd.kzkd,com.xd.kzkd.xindong' AND type='1';
UPDATE game_config SET key_word = '昆仑墟,kunlunxu,klx' WHERE pack_name='com.qdazzle.klx,com.tencent.tmgp.klxol,com.klx.aligames' AND type='1';
UPDATE game_config SET key_word = '彩虹岛W,La Tale W,caihongdaoW,chdW,라테일w' WHERE pack_name='com.gamedreamer.chtw,com.funigloo.latalem' AND type='1';
UPDATE game_config SET key_word = '狼人杀,langrensha,lrs' WHERE pack_name='com.c2vl.kgamebox' AND type='1';
UPDATE game_config SET key_word = '狼人杀(官方正版),langrensha(guanfangzhengban),lrs(gfzb),网易,wangyi,wy' WHERE pack_name='com.netease.lrs' AND type='1';
UPDATE game_config SET key_word = 'Last Battleground:Mech,Last Battleground: Mech,Last Battleground: Survival' WHERE pack_name='com.elex.lastbattlegroundsurvival' AND type='1';
UPDATE game_config SET key_word = '地球末日,Last Day on Earth: Survival,deqiumori,dqmr,地球终日:生存,deqiuzhongri:shengcun,dqzr:sc,Last Day On Earth: Zombie Survival,最后一天:生存' WHERE pack_name='zombie.survival.craft.z' AND type='1';
UPDATE game_config SET key_word = '雷霆战机,leitingzhanji,ltzj' WHERE pack_name='com.tencent.clover' AND type='1';
UPDATE game_config SET key_word = '恋舞OL,lianwuOL,lwOL' WHERE pack_name='com.tencent.tmgp.ddianle.lovedance' AND type='1';
UPDATE game_config SET key_word = '猎人世界,lierenshijie,lrsj' WHERE pack_name='com.gm.lrsj.lm' AND type='1';
UPDATE game_config SET key_word = '光影对决,Light x Shadow,guangyingduijue,gydj,light x shadow' WHERE pack_name='com.dianhun.xgame.lvs,com.tencent.tmgp.dianhun.xgame.lvs' AND type='1';
UPDATE game_config SET key_word = '黎明纪元,limingjiyuan,lmjy' WHERE pack_name='com.zhihuan.games.lmfb' AND type='1';
UPDATE game_config SET key_word = '黎明之光,limingzhiguang,lmzg' WHERE pack_name='com.tencent.tmgp.dbm' AND type='1';
UPDATE game_config SET key_word = '天堂2:革命,Lineage2: Revolution,tiantang2:geming,tt2:gm,revolution' WHERE pack_name='com.netmarble.revolutionthm' AND type='1';
UPDATE game_config SET key_word = '天堂M(台服),LineageM (TW),tiantangM(taifu),ttM(tf)' WHERE pack_name='com.gamania.lineagem' AND type='1';
UPDATE game_config SET key_word = '龙腾传世,longtengchuanshi,ltcs' WHERE pack_name='com.tanwan.ltcs.yy' AND type='1';
UPDATE game_config SET key_word = 'LoveLive! 学园偶像祭(日服),LoveLive! ,LoveLive! xueyuanouxiangji(rifu),LoveLive! xyoxj(rf),LoveLive!' WHERE pack_name='klb.android.lovelive' AND type='1';
UPDATE game_config SET key_word = '乱斗吧勇士,luandoubayongshi,ldbys' WHERE pack_name='com.sy4399.ldbys,com.tencent.tmgp.ldbys,com.ldbys.game' AND type='1';
UPDATE game_config SET key_word = '乱斗西游2,luandouxiyou2,ldxy2,网易乱斗西游2,wangyiluandouxiyou2,wyldxy2' WHERE pack_name='com.tencent.tmgp.ldxy2' AND type='1';
UPDATE game_config SET key_word = '乱轰三国志,luanhongsanguozhi,lhsgz' WHERE pack_name='com.tencent.tmgp.luanhongsgz,com.cj.luanhongsgz.huawei' AND type='1';
UPDATE game_config SET key_word = '轮回诀,lunhuijue,lhj' WHERE pack_name='com.tencent.tmgp.lhj' AND type='1';
UPDATE game_config SET key_word = '洛奇英雄传:永恒,luoqiyingxiongchuan:yongheng,lqyxc:yh' WHERE pack_name='com.tiancity.cmhm.tc,com.tencent.tmgp.tiancity.lqyxz' AND type='1';
UPDATE game_config SET key_word = '玛奇决战,Mabinogi Duel,maqijuezhan,mqjz,瑪奇決戰' WHERE pack_name='com.nexon.devcat.mabinogiduel.global' AND type='1';
UPDATE game_config SET key_word = '漫威:未来之战(国际版),manwei:weilaizhizhan(guojiban),mw:wlzz(gjb),marvel-未來之戰' WHERE pack_name='com.netmarble.mherosgb' AND type='1';
UPDATE game_config SET key_word = '猫和老鼠官方手游,maohelaoshuguanfangshouyou,mhlsgfsy,猫和老鼠,maohelaoshu,mhls,网易,wangyi,wy' WHERE pack_name='com.netease.tjo,com.netease.tom' AND type='1';
UPDATE game_config SET key_word = '冒险岛M(国际版),MapleStory M (Global),maoxiandaoM(guojiban),mxdM(gjb),冒险岛 M(国际版),maoxiandao M(guojiban),mxd M(gjb),冒險島M' WHERE pack_name='com.nexon.maplem.global' AND type='1';
UPDATE game_config SET key_word = '梦间集,mengjianji,mjj' WHERE pack_name='com.tencent.tmgp.mjj' AND type='1';
UPDATE game_config SET key_word = '萌龙大乱斗,menglongdaluandou,mldld,龙之狂热:传奇,longzhikuangre:chuanqi,lzkr:cq,MLDLD' WHERE pack_name='com.gameloft.android.ANMP.GloftDOHM' AND type='1';
UPDATE game_config SET key_word = '梦三国,mengsanguo,msg' WHERE pack_name='com.tencent.tmgp.dianhun.imba3' AND type='1';
UPDATE game_config SET key_word = '秘宝猎人,mibaolieren,mblr,网易,wangyi,wy' WHERE pack_name='com.tencent.tmgp.mblr,com.netease.mblr' AND type='1';
UPDATE game_config SET key_word = '初音速,MikuRun,chuyinsu,cys,网易,wangyi,wy,Hatsune Miku' WHERE pack_name='com.netease.cys,com.tencent.tmgp.yongyong.cys' AND type='1';
UPDATE game_config SET key_word = '我的世界(网易版),Minecraft (NetEase),wodeshijie(wangyiban),wdsj(wyb)' WHERE pack_name='com.netease.mc,com.netease.x19,com.tencent.tmgp.wdsj666,com.netease.wdsj.yyxx.downjoy' AND type='1';
UPDATE game_config SET key_word = '我的世界,Minecraft Pocket Edition,wodeshijie,wdsj,Minecraft PE,沙盒' WHERE pack_name='com.mojang.minecraftpe' AND type='1';
UPDATE game_config SET key_word = '明日之后,mingrizhihou,mrzh,网易,wangyi,wy' WHERE pack_name='com.netease.mrzh' AND type='1';
UPDATE game_config SET key_word = '迷你世界,minishijie,mnsj,3D沙盒' WHERE pack_name='com.tencent.hall.minitech.miniworld,com.tencent.tmgp.minitech.miniworld,com.minitech.miniworld' AND type='1';
UPDATE game_config SET key_word = '團團喵 衝刺！,MitchiriNeko POP,tuantuanmiao chongci！,ttm cc！,みっちりねこ だっしゅ！,团团喵冲刺,团团猫冲刺' WHERE pack_name='jp.co.overfence.mitchirinekodash' AND type='1';
UPDATE game_config SET key_word = '迷雾求生,miwuqiusheng,mwqs,网易,wangyi,wy' WHERE pack_name='com.netease.mwqs,com.tencent.tmgp.yongyong.miwuqiusheng' AND type='1';
UPDATE game_config SET key_word = '迷雾世界,miwushijie,mwsj,网易,wangyi,wy' WHERE pack_name='com.tencent.tmgp.mistworld,com.netease.mistworld' AND type='1';
UPDATE game_config SET key_word = '移动联赛,Mobile League,yidongliansai,ydls,英雄联盟,모바일 리그,移动联盟' WHERE pack_name='com.soma.ml' AND type='1';
UPDATE game_config SET key_word = '敢达 争锋对决,Mobile Suit Gundam,ganda zhengfengduijue,gd zfdj,高达,敢达,机动战士高达,机动战士敢达,争锋对决' WHERE pack_name='com.tencent.tmgp.gundambattle' AND type='1';
UPDATE game_config SET key_word = '现代战争4:决战时刻,Modern Combat 4: Zero Hour,xiandaizhanzheng4:juezhanshike,xdzz4:jzsk,MC4' WHERE pack_name='com.gameloft.android.ANMP.GloftM4HM,com.gameloft.android.AMAZ.GloftM4AS' AND type='1';
UPDATE game_config SET key_word = '现代战争5:眩晕风暴,Modern Combat 5,xiandaizhanzheng5:xuanyunfengbao,xdzz5:xyfb,現代戰爭5：黑影籠罩,ModernCombat5,fps,射击' WHERE pack_name='com.gameloft.android.ANMP.GloftM5HM' AND type='1';
UPDATE game_config SET key_word = '未来特工：精英计划,Modern Combat Versus: New Online Multiplayer FPS,weilaitegong：jingyingjihua,wltg：jyjh,现代战争:尖峰对决,xiandaizhanzheng:jianfengduijue,xdzz:jfdj,现代战争6,Modern Combat Versus: FPS Game,MCVS,MC Versus' WHERE pack_name='com.gameloft.android.ANMP.GloftMVHM' AND type='1';
UPDATE game_config SET key_word = '火线出击 Online,Modern Strike,huoxianchuji Online,hxcj Online,Modern Strike Online,现代出击,FPS' WHERE pack_name='com.gamedevltd.modernstrike' AND type='1';
UPDATE game_config SET key_word = '物語系列 咕噜咕噜,Monogatari Series Pucpuc,wuyuxilie gulugulu,wyxl glgl,〈物語〉シリーズ ぷくぷく,ぷくぷく,物语' WHERE pack_name='com.aniplex.monogataripucpuc' AND type='1';
UPDATE game_config SET key_word = '怪物猎人(台版),Monster Hunter (TW),guaiwulieren(taiban),gwlr(tb),魔物獵人EXPLORE' WHERE pack_name='tw.com.capcom.android.mhxr' AND type='1';
UPDATE game_config SET key_word = '怪物弹珠(日服),Monster Strike (JP),guaiwudanzhu(rifu),gwdz(rf),モンスターストライク,怪物彈珠' WHERE pack_name='jp.co.mixi.monsterstrike' AND type='1';
UPDATE game_config SET key_word = '魔塔守护者Online,motashouhuzheOnline,mtshzOnline' WHERE pack_name='com.starpy.mthxtw' AND type='1';
UPDATE game_config SET key_word = '蘑菇战争2,Mushroom Wars 2,moguzhanzheng2,mgzz2,MW2' WHERE pack_name='com.zillionwhales.mushroomwars2' AND type='1';
UPDATE game_config SET key_word = '奶块,naikuai,nk' WHERE pack_name='com.next.netcraft,com.mcboxol.netcraft' AND type='1';
UPDATE game_config SET key_word = '乃木坂46 Rhythm Festival,naimuban46 Rhythm Festival,nmb46 Rhythm Festival' WHERE pack_name='jp.co.aiia.nogifes' AND type='1';
UPDATE game_config SET key_word = '鸣人X博人,NARUTO X BORUTO,mingrenXboren,mrXbr,NINJA VOLTAGE,忍者BORUTAGE,忍者熱闘,NxBNV' WHERE pack_name='com.bandainamcoent.ninjaborutage_app,com.bandainamcoent.ninjavoltage_app' AND type='1';
UPDATE game_config SET key_word = 'NBA LIVE,NBA LIVE Mobile: 勁爆美國職籃' WHERE pack_name='com.ea.gp.nbamobile_sea,com.tencent.tmgp.ea.android.chs.nbamobile,com.ea.gp.nbamobile' AND type='1';
UPDATE game_config SET key_word = '新剑与魔法,New Sword and Magic,xinjianyumofa,xjymf' WHERE pack_name='com.longtugame.jymfdsj.longtu,com.longtugame.jymf,com.tencent.tmgp.jymfdsj' AND type='1';
UPDATE game_config SET key_word = 'Ingress,Niantic,pokemon go,pmgo' WHERE pack_name='com.nianticproject.ingress' AND type='1';
UPDATE game_config SET key_word = '阴阳师(港台服),Onmyoji (HKTW),yinyangshi(gangtaifu),yys(gtf),阴阳师港台服,yinyangshigangtaifu,yysgtf,阴阳师海外服,yinyangshihaiwaifu,yyshwf,网易阴阳师港台服,wangyiyinyangshigangtaifu,wyyysgtf,Onmyoji' WHERE pack_name='com.netease.onmyoji.na' AND type='1';
UPDATE game_config SET key_word = '阴阳师(日服),Onmyoji (JP),yinyangshi(rifu),yys(rf),陰陽師Onmyoji 和風幻想RPG,网易,wangyi,wy' WHERE pack_name='com.netease.onmyoji.na' AND type='1';
UPDATE game_config SET key_word = '阴阳师(韩服),Onmyoji (KR),yinyangshi(hanfu),yys(hf),음양사-for-kakao' WHERE pack_name='com.kakaogames.onmyouji' AND type='1';
UPDATE game_config SET key_word = '混沌与秩序OL,Order & Chaos OL,hundunyuzhixuOL,hdyzxOL,Order & Chaos Online - Fantasy 3D MMORPG' WHERE pack_name='com.gameloft.android.ANMP.GloftMMHM' AND type='1';
UPDATE game_config SET key_word = 'OverHit(日韩),OverHit(JP&HR),OverHit(rihan),OverHit(rh),OVERHIT(日版),OVERHIT(JP),OVERHIT(riban),OVERHIT(rb),OVERHIT日服,OVERHITrifu,OVERHITrf,OVERHIT,오버히트' WHERE pack_name='com.nexon.overhit.japan,com.nexon.overhit' AND type='1';
UPDATE game_config SET key_word = '枪火游侠,Paladins Strike,qianghuoyouxia,qhyx' WHERE pack_name='com.djwl.PLD3' AND type='1';
UPDATE game_config SET key_word = '跑跑卡丁车手游,paopaokadingcheshouyou,ppkdcsy' WHERE pack_name='com.tiancity.paopao.ewan.tencent,com.mpopkart.wdj' AND type='1';
UPDATE game_config SET key_word = 'PES 2018,PES 2017,pes 2018,PRO EVOLUTION SOCCER,实况足球俱乐部,实况足球2017,shikuangzuqiu,zuqiu,soccer,2018' WHERE pack_name='jp.konami.pesam' AND type='1';
UPDATE game_config SET key_word = '影之刃2,Phantom Blade 2,yingzhiren2,yzr2' WHERE pack_name='m.Sgame.yzr2.SplashActivity,com.herogame.gplay.yzrtw,com.tencent.tmgp.yzr2,com.yzr2.az.uc,com.shouyou.yzr2.sw,m.Sgame.yzr2' AND type='1';
UPDATE game_config SET key_word = '像素射击,Pixel Gun 3D,xiangsusheji,xssj,像素枪战' WHERE pack_name='com.pixel.gun3d,com.pixel.gun3dmod,com.pixel.gun3d.abc' AND type='1';
UPDATE game_config SET key_word = '像素生存游戏2,Pixel Survival 2,xiangsushengcunyouxi2,xsscyx2,像素生存,xiangsushengcun,xssc,pixel survival 2' WHERE pack_name='com.cowbeans.pixelsurvival2' AND type='1';
UPDATE game_config SET key_word = '英雄行星,Planet of Heroes,yingxiongxingxing,yxxx' WHERE pack_name='com.my.moba.ent' AND type='1';
UPDATE game_config SET key_word = 'POKEMMO' WHERE pack_name='eu.pokemmo.client' AND type='1';
UPDATE game_config SET key_word = '宝可梦探险寻宝,Pokemon Quest,baokemengtanxianxunbao,bkmtxxb,寶可夢探險尋寶,pokemon quest,baokemeng tanxianxunbao,bkm txxb' WHERE pack_name='jp.pokemon.pokemonquest' AND type='1';
UPDATE game_config SET key_word = 'PlayStation App,PSAPP' WHERE pack_name='com.scee.psxandroid' AND type='1';
UPDATE game_config SET key_word = '刺激战场(欧服),PUBG Mobile (EU),cijizhanchang(oufu),cjzc(of),绝地求生:刺激战场(欧服),juedeqiusheng:cijizhanchang(oufu),jdqs:cjzc(of)' WHERE pack_name='com.tencent.ig' AND type='1';
UPDATE game_config SET key_word = '智龙迷城(日服),Puzzle & Dragons (JP),zhilongmicheng(rifu),zlmc(rf)' WHERE pack_name='jp.gungho.pad' AND type='1';
UPDATE game_config SET key_word = '枪火战神,qianghuozhanshen,qhzs' WHERE pack_name='com.tencent.tmgp.yxsm' AND type='1';
UPDATE game_config SET key_word = '青春篮球,qingchunlanqiu,qclq' WHERE pack_name='com.xd.basketBall' AND type='1';
UPDATE game_config SET key_word = '青云剑道,qingyunjiandao,qyjd' WHERE pack_name='com.four.blue.qyjd' AND type='1';
UPDATE game_config SET key_word = '齐天战神,qitianzhanshen,qtzs' WHERE pack_name='com.tencent.tmgp.qitianzs,com.luomo.qitianzs1.chujian,wp.midlet.MonkeyLengendNewMM' AND type='1';
UPDATE game_config SET key_word = '契约勇士,qiyueyongshi,qyys' WHERE pack_name='com.xunyang.qyys.guopan' AND type='1';
UPDATE game_config SET key_word = '全民超神,quanminchaoshen,qmcs' WHERE pack_name='com.tencent.tmgp.gods' AND type='1';
UPDATE game_config SET key_word = '全民奇迹,quanminqiji,qmqj' WHERE pack_name='com.tianmashikong.qmqj.apps,com.qmqj.tianmashikong,com.tencent.tmgp.tianmashikong.qj,com.tianmashikong.qmqj,com.Tianma.QiJi.UC' AND type='1';
UPDATE game_config SET key_word = '全民突击,quanmintuji,qmtj' WHERE pack_name='com.tencent.WeFire' AND type='1';
UPDATE game_config SET key_word = '全职高手,quanzhigaoshou,qzgs' WHERE pack_name='com.fl.qzgs.feiliu,com.tencent.tmgp.qzgs' AND type='1';
UPDATE game_config SET key_word = '去吧皮卡丘,qubapikaqiu,qbpkq,热血精灵王,rexuejinglingwang,rxjlw' WHERE pack_name='net.crimoon.pmdk,com.tencent.tmgp.yinhan.crimoonpm4' AND type='1';
UPDATE game_config SET key_word = '辐射岛,Radiation Island,fushedao,fsd' WHERE pack_name='com.atypicalgames.radiationisland' AND type='1';
UPDATE game_config SET key_word = 'Raven:掠夺者,Raven:lveduozhe,Raven:ldz,Ravenlveduozhe,Ravenldz,Raven lveduozhe,Raven ldz,掠夺者,Raven lueduozhe,lueduozhe,wangyilveduozhe,wyldz,网易' WHERE pack_name='com.netease.raven,com.netease.ravcn,com.tencent.tmgp.raven' AND type='1';
UPDATE game_config SET key_word = '真实赛车3,Real Racing 3,zhenshisaiche3,zssc3' WHERE pack_name='com.ea.games.r3_row' AND type='1';
UPDATE game_config SET key_word = '秘境对决,Realm of Duels,mijingduijue,mjdj,wangyi,网易,wy' WHERE pack_name='com.netease.mjdjx16' AND type='1';
UPDATE game_config SET key_word = 'Roblox手游,Roblox mobile,Robloxshouyou,Robloxsy,Roblox' WHERE pack_name='com.roblox.client' AND type='1';
UPDATE game_config SET key_word = '荣耀继承者,rongyaojichengzhe,ryjcz,榮耀繼承者' WHERE pack_name='com.gamevil.heiroflight.android.google.global.normal' AND type='1';
UPDATE game_config SET key_word = '如果的世界,ruguodeshijie,rgdsj' WHERE pack_name='com.tencent.tmgp.areal' AND type='1';
UPDATE game_config SET key_word = '三国杀OL互通版,sanguoshaOLhutongban,sgsOLhtb' WHERE pack_name='com.gameabc.sgspad,com.sanguosha.sgsol,com.sanguosha.sgsolabaidu.BD,com.sanguosha.sgsolaxiaomi.mi,com.sanguosha.sgsolauc.uc,com.sanguosha.sgsola360_1,com.tencent.tmgp.sanguosha' AND type='1';
UPDATE game_config SET key_word = '三国志2017,sanguozhi2017,sgz2017' WHERE pack_name='com.shouyou.sgzerq.bg' AND type='1';
UPDATE game_config SET key_word = '三国志烈伝,sanguozhilieyun,sgzly,dragon blade,乱轰三国志' WHERE pack_name='com.yh.lhsgz.yh' AND type='1';
UPDATE game_config SET key_word = '三国之刃,sanguozhiren,sgzr' WHERE pack_name='com.tencent.tmgp.sgzr' AND type='1';
UPDATE game_config SET key_word = '三少爷的剑,sanshaoyedejian,ssydj,网易,wangyi,wy' WHERE pack_name='com.netease.ssy,com.netease.ssydj' AND type='1';
UPDATE game_config SET key_word = '刀剑神域:记忆重组 国际服,SAO MD (HKTW),daojianshenyu:jiyizhongzu guojifu,djsy:jyzz gjf,daojianshenyu:jiyisuipian guojifu,djsy:jysp gjf,刀剑神域：记忆重组,daojianshenyu：jiyisuipian,djsy：jysp,saomd,记忆重组,记忆碎片,港台服国际服外服,SWORD ART ONLINE:Memory Defrag' WHERE pack_name='com.bandainamcoent.saomdas,jp.co.bandainamcoent.BNEI0294' AND type='1';
UPDATE game_config SET key_word = '战国阿修罗,Sengoku ASURA,zhanguoaxiuluo,zgaxl,战国ASURA,zhanguoASURA,zgASURA,戰國阿修羅,戦国ASURA' WHERE pack_name='jp.co.sumzap.pj0002' AND type='1';
UPDATE game_config SET key_word = '七雄战记,Seven Guardians,qixiongzhanji,qxzj,七雄战记：最后的守护者,qixiongzhanji：zuihoudeshouhuzhe,外服' WHERE pack_name='com.ftt.sevenguardians.gl.global' AND type='1';
UPDATE game_config SET key_word = '七騎士,Seven Knights,qiqishi,qqs,七骑士' WHERE pack_name='com.netmarble.sknightsgb' AND type='1';
UPDATE game_config SET key_word = '商店英雄,shangdianyingxiong,sdyx,Shop Heroes' WHERE pack_name='com.cloudcade.shopheroes' AND type='1';
UPDATE game_config SET key_word = '山海启示录,shanhaiqishilu,shqsl' WHERE pack_name='com.yinhu.sdk.fxy.pj' AND type='1';
UPDATE game_config SET key_word = '少年西游记,shaonianxiyouji,snxyj' WHERE pack_name='com.tencent.tmgp.yzsnxyj,com.snxyj.apk.nearme.gamecenter' AND type='1';
UPDATE game_config SET key_word = '少女咖啡枪,shaonvkafeiqiang,snkfq' WHERE pack_name='com.tencent.tmgp.xsj.girlcafegun,com.xsj.girlcafegun' AND type='1';
UPDATE game_config SET key_word = '射雕英雄传3D,shediaoyingxiongchuan3D,sdyxc3D' WHERE pack_name='com.tencent.tmgp.meiqi.sdyxz.android' AND type='1';
UPDATE game_config SET key_word = '神代梦华谭,shendaimenghuatan,sdmht' WHERE pack_name='com.bilibili.BulletBible.bili,com.tencent.tmgp.bilibili.sdmht' AND type='1';
UPDATE game_config SET key_word = '生死狙击,shengsijuji,ssjj' WHERE pack_name='com.wooduan.ssjj,com.tencent.tmgp.wooduan.ssjj' AND type='1';
UPDATE game_config SET key_word = '神话永恒,shenhuayongheng,shyh' WHERE pack_name='com.tencent.tmgp.cmge.myth' AND type='1';
UPDATE game_config SET key_word = '神女控,shennvkong,snk,valkyrie-crusade' WHERE pack_name='com.nubee.valkyriecrusade' AND type='1';
UPDATE game_config SET key_word = '神位纷争,shenweifenzheng,swfz' WHERE pack_name='com.smiletech.ragnania.alpha' AND type='1';
UPDATE game_config SET key_word = '神无月,shenwuyue,swy' WHERE pack_name='com.shandagames.DEVINE,com.tencent.tmgp.DEVINE' AND type='1';
UPDATE game_config SET key_word = '深渊地平线,shenyuandepingxian,sydpx,アビホラ,アビス・ホライズン' WHERE pack_name='com.morningtec.abyss' AND type='1';
UPDATE game_config SET key_word = '蛇蛇大作战,sheshedazuozhan,ssdzz' WHERE pack_name='com.tuanzi.sheshe,air.com.hypah.io.slither' AND type='1';
UPDATE game_config SET key_word = '蛇蛇争霸,sheshezhengba,sszb' WHERE pack_name='com.tencent.tmgp.bairimeng.snake,com.bairimeng.snake' AND type='1';
UPDATE game_config SET key_word = '时空猎人,shikonglieren,sklr' WHERE pack_name='com.yinhan.hunter' AND type='1';
UPDATE game_config SET key_word = '时空召唤,shikongzhaohuan,skzh' WHERE pack_name='cn.yh.cos,com.yinhan.skzh,com.tencent.tmgp.yinhan.skzh' AND type='1';
UPDATE game_config SET key_word = '实况:王者集结,shikuang:wangzhejijie,sk:wzjj,网易,wangyi,wy' WHERE pack_name='com.netease.wecc' AND type='1';
UPDATE game_config SET key_word = '十万个冷笑话,shiwangelengxiaohua,swglxh' WHERE pack_name='com.tencent.tmgp.cjad' AND type='1';
UPDATE game_config SET key_word = '曙光破晓,shuguangpoxiao,sgpx' WHERE pack_name='com.zhuiqu.sg.tap,com.tencent.tmgp.sgpx' AND type='1';
UPDATE game_config SET key_word = '模拟城市,SimCity BuildIt,monichengshi,mncs' WHERE pack_name='com.ea.game.simcitymobile_row,com.eagames.simcity.qihoo360' AND type='1';
UPDATE game_config SET key_word = '死亡爱丽丝,SINoALICE,siwangailisi,swals,SINo爱丽丝,SINoailisi,SINoals,シノアリス,SINoALICE ーシノアリスー' WHERE pack_name='jp.co.pokelabo.sinoalice' AND type='1';
UPDATE game_config SET key_word = '炽热狙击,Sniper Fury,chirejuji,crjj' WHERE pack_name='com.gameloft.android.ANMP.GloftFWHM' AND type='1';
UPDATE game_config SET key_word = '元气骑士,Soul Knight,yuanqiqishi,yqqs,soul knight' WHERE pack_name='com.ChillyRoom.DungeonShooter,com.liangwu.yuanqiqishi.vivo,yuanqiqishi.game.mz,com.jingmo.knight,com.tencent.tmgp.yqqskp,com.Yuanqi.qishi' AND type='1';
UPDATE game_config SET key_word = '特种部队小组2,Special Forces Group 2,tezhongbuduixiaozu2,tzbdxz2,csgo,SFG2,反恐精英' WHERE pack_name='com.ForgeGames.SpecialForcesGroup2' AND type='1';
UPDATE game_config SET key_word = '蜘蛛侠:极限,Spider-Man Unlimited,zhizhuxia:jixian,zzx:jx,MARVEL Spider-Man Unlimited,蜘蛛人：飛越無限' WHERE pack_name='com.gameloft.android.ANMP.GloftSIHM' AND type='1';
UPDATE game_config SET key_word = '星球大战:银河英雄传,Star Wars™:Galaxy of Heroes,xingqiudazhan:yinheyingxiongchuan,xqdz:yhyxc,Star Wars™: Galaxy of Heroes' WHERE pack_name='com.ea.game.starwarscapital_row' AND type='1';
UPDATE game_config SET key_word = '速度与激情8,suduyujiqing8,sdyjq8' WHERE pack_name='com.hzfb.racing8' AND type='1';
UPDATE game_config SET key_word = '超级马里奥酷跑,Super Mario Run,chaojimaliaokupao,cjmlakp,超级马里奥,chaojimaliao,cjmla,mla,SMR,外服' WHERE pack_name='com.nintendo.zara' AND type='1';
UPDATE game_config SET key_word = 'Squad(美服),Survival Squad(meifu),Survival Squad(mf)' WHERE pack_name='com.q1.survival	Survival' AND type='1';
UPDATE game_config SET key_word = 'Squad(亚服),Survival Squad(yafu),Survival Squad(yf),Survival Squad' WHERE pack_name='com.q1.survival	Survival' AND type='1';
UPDATE game_config SET key_word = '刀剑神域 Integral Factor,Sword Art Online Integral Factor,daojianshenyu Integral Factor,djsy Integral Factor,ソードアート・オンライン インテグラル・ファクター,SAOIF' WHERE pack_name='com.bandainamcoent.saoif' AND type='1';
UPDATE game_config SET key_word = '刀剑神域:关键斗士(国际版),Sword Art Online Integral Factor,daojianshenyu:guanjiandoushi(guojiban),djsy:gjds(gjb),刀剑神域:关键斗士,daojianshenyu:guanjiandoushi,djsy:gjds,刀劍神域:關鍵鬥士' WHERE pack_name='com.bandainamcoent.saoifww' AND type='1';
UPDATE game_config SET key_word = '剑之荣耀,Sword of Glory (CN),jianzhirongyao,jzry' WHERE pack_name='com.tencent.tmgp.jzryv1,com.android.ninefun.mmo' AND type='1';
UPDATE game_config SET key_word = '太极熊猫,taijixiongmao,tjxm' WHERE pack_name='com.snailgames.taiji,com.tencent.tmgp.tjxm,com.snailgameusa.tp' AND type='1';
UPDATE game_config SET key_word = '太极熊猫3:猎龙,taijixiongmao3:lielong,tjxm3:ll' WHERE pack_name='com.tencent.tmgp.kaopu.tjxm3' AND type='1';
UPDATE game_config SET key_word = '贪吃蛇大作战,tanchishedazuozhan,tcsdzz,贪食蛇大作战,tanshishedazuozhan,tssdzz' WHERE pack_name='com.wepie.snakegame,com.wepie.snake,com.wepie.snakeoff' AND type='1';
UPDATE game_config SET key_word = '坦克连,Tank Company,tankelian,tkl,网易,wangyi,wy' WHERE pack_name='com.netease.tank' AND type='1';
UPDATE game_config SET key_word = '桃花源记,taohuayuanji,thyj' WHERE pack_name='com.taole.pisces_tlp,com.tencent.tmgp.pisces' AND type='1';
UPDATE game_config SET key_word = '逃跑吧！少年,taopaoba！shaonian,tpb！sn,逃跑吧少年' WHERE pack_name='com.tencent.tmgp.bairimeng.dmmdzz,com.bairimeng.dmmdzz' AND type='1';
UPDATE game_config SET key_word = '铁拳,TEKKEN™ ,tiequan,tq,TEKKEN™,鐵拳 - TEKKEN™ -' WHERE pack_name='eu.bandainamcoent.tekkenmobile' AND type='1';
UPDATE game_config SET key_word = '泰拉瑞亚,Terraria,tailaruiya,tlry' WHERE pack_name='com.idreamsky.terraria,com.505games.terraria,com.and.games505.TerrariaPaid,com.and.games505.Terraria' AND type='1';
UPDATE game_config SET key_word = '为了谁的炼金术士(日服),The Alchemist Code (JP),weilesheidelianjinshushi(rifu),wlsdljss(rf),誰ガ為のアルケミスト' WHERE pack_name='jp.co.gu3.alchemist' AND type='1';
UPDATE game_config SET key_word = '为了谁的炼金术士(台服),The Alchemist Code (TW),weilesheidelianjinshushi(taifu),wlsdljss(tf)' WHERE pack_name='com.denachina.g23000114.android' AND type='1';
UPDATE game_config SET key_word = '偶像大师:百万现场!剧场时光,The Idolmaster:Million Live!,ouxiangdashi:baiwanxianchang!juchangshiguang,oxds:bwxc!jcsg,アイドルマスター ミリオンライブ！ シアターデイズ,ミリシタ,ouxiangdashibaiwanxianchangjuchangshiguang' WHERE pack_name='com.bandainamcoent.imas_millionlive_theaterdays' AND type='1';
UPDATE game_config SET key_word = '模拟人生™:畅玩版,The Sims™ FreePlay,monirensheng™:changwanban,mnrs™:cwb,模拟人生,monirensheng' WHERE pack_name='com.ea.games.simsfreeplay_row,com.ea.sims3deluxe.ipad.bv,com.ea.games.simsfreeplay_na' AND type='1';
UPDATE game_config SET key_word = '模拟市民,The Sims™ Mobile,monishimin,mnsm,The Sims 模擬市民手機版,模拟人生' WHERE pack_name='com.ea.gp.simsmobile' AND type='1';
UPDATE game_config SET key_word = '边境之旅,The Trail (CN),bianjingzhilv,bjzl,网易,wangyi,wy' WHERE pack_name='com.tencent.tmgp.ma71,com.netease.ma71' AND type='1';
UPDATE game_config SET key_word = '行尸走肉:无人之地,The Walking Dead: No Man’s Land,xingshizourou:wurenzhidi,xszr:wrzd' WHERE pack_name='com.nextgames.android.twd,com.nextgames.twd,com.xingshirouzowu' AND type='1';
UPDATE game_config SET key_word = '狼族,The Wolf,langzu,lz,The Wolf: Online RPG Simulator,Wild animal multiplayer battle' WHERE pack_name='com.swiftappskom.thewolfrpg' AND type='1';
UPDATE game_config SET key_word = '魔法世界,The World of Magic,mofashijie,mfsj' WHERE pack_name='com.com2us.imo.normal.freefull.google.global.android.common' AND type='1';
UPDATE game_config SET key_word = '天华百剑 -斩-,tianhuabaijian -zhan-,thbj -z-,天華百剣 -斬-' WHERE pack_name='com.dena.a12022874' AND type='1';
UPDATE game_config SET key_word = '天空守望者,tiankongshouwangzhe,tkswz' WHERE pack_name='com.blazefire.tkswz.tuanwan' AND type='1';
UPDATE game_config SET key_word = '天龙3D,tianlong3D,tl3D' WHERE pack_name='com.tencent.tmgp.mtlbb' AND type='1';
UPDATE game_config SET key_word = '天启联盟,tianqilianmeng,tqlm,网易,wangyi,wy' WHERE pack_name='com.tencent.tmgp.yongyong.tqlm,com.netease.tqlm' AND type='1';
UPDATE game_config SET key_word = '天生不凡,tianshengbufan,tsbf' WHERE pack_name='com.wanda.hjl.wdgw' AND type='1';
UPDATE game_config SET key_word = '天堂2:血盟,tiantang2:xuemeng,tt2:xm' WHERE pack_name='com.tencent.tmgp.tt2xmysdk,com.snailgame.lineage' AND type='1';
UPDATE game_config SET key_word = '天堂M(韩服),tiantangM(hanfu),ttM(hf),리니지M' WHERE pack_name='com.ncsoft.lineagem19' AND type='1';
UPDATE game_config SET key_word = '天天富翁,tiantianfuweng,ttfw' WHERE pack_name='com.tencent.modoomarble,com.tencent.moma' AND type='1';
UPDATE game_config SET key_word = '天天狼人杀,tiantianlangrensha,ttlrs,狼人杀' WHERE pack_name='sdbean.MegaWerewolf,com.sdbean.werewolf' AND type='1';
UPDATE game_config SET key_word = '天天炫斗,tiantianxuandou,ttxd' WHERE pack_name='com.tencent.game.VXDGame' AND type='1';
UPDATE game_config SET key_word = '刀使的巫女:刻印一闪的灯火,Toji no Miko:Kizamishi Issen no Tomoshibi,daoshidewunv:keyinyishandedenghuo,dsdwn:kyysddh,刀使ノ巫女 刻みし一閃の燈火,刀使巫女' WHERE pack_name='com.square_enix.android_googleplay.TojinomikoTomoshibi' AND type='1';
UPDATE game_config SET key_word = '东京七姐妹,Tokyo 7th Sister,dongjingqijiemei,djqjm,東京第7姐妹,Tokyo 7th シスターズ' WHERE pack_name='jp.ne.donuts.t7s' AND type='1';
UPDATE game_config SET key_word = '托兰异世录,Toram Online,tuolanyishilu,tlysl,托蘭異世錄,トーラムオンライン' WHERE pack_name='com.asobimo.toramonline' AND type='1';
UPDATE game_config SET key_word = '刀剣乱舞(日服),Touken Ranbu (JP),daojianluanwu(rifu),djlw(rf),刀剑乱舞日服,刀剣乱舞-ONLINE- Pocket,Touken Ranbu Online' WHERE pack_name='com.dmm.games.touken' AND type='1';
UPDATE game_config SET key_word = '梦想小镇,Township,mengxiangxiaozhen,mxxz,township' WHERE pack_name='com.playrix.township' AND type='1';
UPDATE game_config SET key_word = '特技摩托：前线,Trials Frontier,tejimotuo：qianxian,tjmt：qx,特技摩托賽：前線' WHERE pack_name='com.ubisoft.redlynx.trialsfrontier.ggp' AND type='1';
UPDATE game_config SET key_word = 'TT语音,TTyuyin,TTyy' WHERE pack_name='com.yiyou.ga' AND type='1';
UPDATE game_config SET key_word = '托拉姆物语,tuolamuwuyu,tlmwy' WHERE pack_name='com.xiaoyou.ToramOnline,com.xiaoyou.ToramOnline.aligames.uc,com.xiaoyou.ToramOnline360' AND type='1';
UPDATE game_config SET key_word = '神托的使徒×终焉的女神,UNITIA,UNITIA shentuodeshitu×zhongyandenvshen,UNITIA stdst×zydns,UNITIA 神託の使徒×終焉の女神,UNITIA shentuoのshitu×zhongyanのnvshen,UNITIA stのst×zyのns,DMM,ユニティア' WHERE pack_name='com.dmm.games.unitia.tc	UNITIA' AND type='1';
UPDATE game_config SET key_word = '优诺纸牌,UNO ™ & Friends,younuozhipai,ynzp' WHERE pack_name='com.gameloft.android.ANMP.GloftUOHM' AND type='1';
UPDATE game_config SET key_word = '虚荣(亚服),Vainglory (AS),xurong(yafu),xr(yf),虚荣(海外服),Vainglory (Oversea),xurong(haiwaifu),xr(hwf),虚荣,xurong,xr,Vainglory,moba,海外服' WHERE pack_name='com.superevilmegacorp.game,com.superevilmegacorp.kindred' AND type='1';
UPDATE game_config SET key_word = '虚荣(国服),Vainglory (CN),xurong(guofu),xr(gf),vainglory,VG' WHERE pack_name='com.superevilmegacorp.kindred,com.superevilmegacorp.game' AND type='1';
UPDATE game_config SET key_word = '虚荣(欧服),Vainglory (EU),xurong(oufu),xr(of)' WHERE pack_name='com.superevilmegacorp.game,com.superevilmegacorp.kindred' AND type='1';
UPDATE game_config SET key_word = '虚荣(美服),Vainglory (US),xurong(meifu),xr(mf)' WHERE pack_name='com.superevilmegacorp.game,com.superevilmegacorp.kindred' AND type='1';
UPDATE game_config SET key_word = '神域召唤,Valkyrie Connect,shenyuzhaohuan,syzh,外服' WHERE pack_name='jp.co.atm.vcon.ww,jp.co.atm.vcon.jp' AND type='1';
UPDATE game_config SET key_word = '绝处逢生,Vast Survival,juechufengsheng,jcfs,Vast Survival (Multiplayer),H1Z1,外服,fps,射击' WHERE pack_name='com.hoodoogames.vast' AND type='1';
UPDATE game_config SET key_word = '蘭空,VOEZ lankong,VOEZ lk' WHERE pack_name='com.rayark.valkyrie	VOEZ 兰空,VOEZ' AND type='1';
UPDATE game_config SET key_word = '忘仙,wangxian,wx' WHERE pack_name='org.cocos2dx.tests,org.mieshiqq' AND type='1';
UPDATE game_config SET key_word = '王者军团,wangzhejuntuan,wzjt' WHERE pack_name='com.tnyoo.fps,com.tencent.tmgp.fps.tnyoo.android' AND type='1';
UPDATE game_config SET key_word = '王者荣耀前瞻版,wangzherongyaoqianzhanban,wzryqzb,王者荣耀体验服' WHERE pack_name='com.tencent.tmgp.sgamece,com.tencent.tmgp.sgamece-ext' AND type='1';
UPDATE game_config SET key_word = '玩具大乱斗,wanjudaluandou,wjdld,网易,wangyi,wy' WHERE pack_name='com.netease.wjdld,com.tencent.tmgp.wjdld' AND type='1';
UPDATE game_config SET key_word = '万象物语,wanxiangwuyu,wxwy,Sdorica' WHERE pack_name='com.ilongyuan.sdorica.longyuan,com.rayark.sdorica' AND type='1';
UPDATE game_config SET key_word = '战争机器人,War Robots,zhanzhengjiqiren,zzjqr,进击的战争武器,jjdzzwq' WHERE pack_name='com.pixonic.wwr' AND type='1';
UPDATE game_config SET key_word = '战争之歌,War Song,zhanzhengzhige,zzzg,War Song(Unreleased),ウォーソング,王者荣耀日服' WHERE pack_name='com.sixjoy.warsong1' AND type='1';
UPDATE game_config SET key_word = '浴血长空(亚服),War Wings (AS),yuxuezhangkong(yafu),yxzk(yf),War Wings' WHERE pack_name='com.tencent.warwings2' AND type='1';
UPDATE game_config SET key_word = '浴血长空(澳服),War Wings (AU),yuxuezhangkong(aofu),yxzk(af),War Wings' WHERE pack_name='com.tencent.warwings2' AND type='1';
UPDATE game_config SET key_word = '浴血长空(欧服),War Wings (EU),yuxuezhangkong(oufu),yxzk(of),浴血長空,War Wings' WHERE pack_name='com.tencent.warwings2' AND type='1';
UPDATE game_config SET key_word = '浴血长空(美服),War Wings (US),yuxuezhangkong(meifu),yxzk(mf),浴血長空,War Wings' WHERE pack_name='com.tencent.warwings2' AND type='1';
UPDATE game_config SET key_word = '战矛在线,Warspear Online,zhanmaozaixian,zmzx' WHERE pack_name='com.aigrind.warspear' AND type='1';
UPDATE game_config SET key_word = '为谁而炼金,weisheierlianjin,wselj' WHERE pack_name='com.denachina.g13002001.denacn' AND type='1';
UPDATE game_config SET key_word = '伪装女友,weizhuangnvyou,wzny,ニセカノ〜チャットでアイドルと恋愛しよう〜' WHERE pack_name='jp.co.freep.usokano' AND type='1';
UPDATE game_config SET key_word = '西部世界,Westworld,xibushijie,xbsj' WHERE pack_name='com.wb.goog.westworld' AND type='1';
UPDATE game_config SET key_word = '白猫计划(台服),White Cat Project (TW),baimaojihua(taifu),bmjh(tf),白貓Project' WHERE pack_name='tw.sonet.wcp' AND type='1';
UPDATE game_config SET key_word = '丛林法则,Wild Animals Online,conglinfaze,clfz,WAO' WHERE pack_name='com.hanaGames.WildAnimalsOnline' AND type='1';
UPDATE game_config SET key_word = '我的战争,wodezhanzheng,wdzz' WHERE pack_name='com.gaea.yszz,com.tencent.tmgp.yszz,com.gaea.wdzz' AND type='1';
UPDATE game_config SET key_word = '卧虎藏龙,wohucanglong,whcl' WHERE pack_name='com.tencent.tmgp.wohucanglong,com.sqage.Ogre.OgreInstance' AND type='1';
UPDATE game_config SET key_word = '卧虎藏龙2,wohucanglong2,whcl2,卧虎藏龙贰' WHERE pack_name='com.aligames.sqage.xtxj,com.tencent.tmgp.yongyong.whcl' AND type='1';
UPDATE game_config SET key_word = '我叫MT2,wojiaoMT2,wjMT2' WHERE pack_name='com.tencent.tmgp.mt2' AND type='1';
UPDATE game_config SET key_word = '我叫MT开荒团,wojiaoMTkaihuangtuan,wjMTkht' WHERE pack_name='com.istorm.kht.gw,com.tencent.tmgp.kht' AND type='1';
UPDATE game_config SET key_word = '最终幻想世界:怪兽养成,World of Final Fantasy:Meli-Melo,zuizhonghuanxiangshijie:guaishouyangcheng,zzhxsj:gsyc,MERIMERO,WFFMM' WHERE pack_name='com.square_enix.android_googleplay.WOFFMeliMeloj' AND type='1';
UPDATE game_config SET key_word = '坦克世界闪击战,World of Tank Blitz (CN),tankeshijieshanjizhan,tksjsjz,网易,wangyi,wy' WHERE pack_name='com.tencent.tmgp.yongyong.tksjsjz,com.netease.wotb' AND type='1';
UPDATE game_config SET key_word = '坦克世界:闪电战,World of Tanks Blitz,tankeshijie:shandianzhan,tksj:sdz,坦克世界：闪电战,tankeshijie：shandianzhan,tksj：sdz,坦克世界：闪击战,tankeshijie：shanjizhan,tksj：sjz' WHERE pack_name='net.wargaming.wot.blitz,net.wargaming.wotblitz' AND type='1';
UPDATE game_config SET key_word = '战舰世界:闪电战,World of Warships Blitz,zhanjianshijie:shandianzhan,zjsj:sdz,WOWSB,战舰世界闪击战' WHERE pack_name='net.wargaming.wows.blitz' AND type='1';
UPDATE game_config SET key_word = '世界战争-英雄,World War Heroes,shijiezhanzheng-yingxiong,sjzz-yx,二战英雄,erzhanyingxiong,ezyx,世界大战英雄,wwh,shijiedazhanyingxiong,sjdzyx' WHERE pack_name='com.gamedevltd.wwh' AND type='1';
UPDATE game_config SET key_word = '无尽战区:觉醒,wujinzhanqu:juexing,wjzq:jx,网易,wangyi,wy' WHERE pack_name='com.tencent.tmgp.wjzqjx,com.netease.wjzqjx' AND type='1';
UPDATE game_config SET key_word = '五行天手游,wuxingtianshouyou,wxtsy' WHERE pack_name='com.idreamsky.worldoffiveelements,com.tencent.tmgp.wuxingtian' AND type='1';
UPDATE game_config SET key_word = '香肠派对,xiangchangpaidui,xcpd,战斗岛' WHERE pack_name='com.sofunny.Chicken' AND type='1';
UPDATE game_config SET key_word = '像素求生:大逃杀,xiangsuqiusheng:dataosha,xsqs:dts,Pixel Battleground' WHERE pack_name='com.thosecoolguys.pbg' AND type='1';
UPDATE game_config SET key_word = '仙剑奇侠传幻璃镜,xianjianqixiachuanhuanlijing,xjqxchlj' WHERE pack_name='com.softstargames.hlj,com.tencent.tmgp.huanlijing' AND type='1';
UPDATE game_config SET key_word = '仙剑奇侠传online,xianjianqixiachuanonline,xjqxconline' WHERE pack_name='com.tencent.tmgp.palol' AND type='1';
UPDATE game_config SET key_word = '仙剑云之凡,xianjianyunzhifan,xjyzf' WHERE pack_name='com.csj.xianjian.xjyzf' AND type='1';
UPDATE game_config SET key_word = '仙灵大作战,xianlingdazuozhan,xldzz' WHERE pack_name='com.tencent.tmgp.zhizhu.xldzz,com.jingmo.zzxy' AND type='1';
UPDATE game_config SET key_word = '小冰冰传奇,xiaobingbingchuanqi,xbbcq,刀塔传奇,daotachuanqi,dtcq' WHERE pack_name='com.tencent.tmgp.lilith_dtcq' AND type='1';
UPDATE game_config SET key_word = '消除者联盟,xiaochuzhelianmeng,xczlm' WHERE pack_name='com.tencent.tmgp.wesix' AND type='1';
UPDATE game_config SET key_word = '小米枪战,Xiaomi Gun Battle (CN),xiaomiqiangzhan,xmqz' WHERE pack_name='com.ak.mi,com.tencent.tmgp.ak' AND type='1';
UPDATE game_config SET key_word = '小米超神,Xiaomi Legend,xiaomichaoshen,xmcs,moba' WHERE pack_name='me.zhuque.moba.mi,me.zhuque.moba.GameActivity,me.zhuque.moba.taste' AND type='1';
UPDATE game_config SET key_word = '小小突击队,xiaoxiaotujidui,xxtjd' WHERE pack_name='com.tencent.tmgp.xxtjd,com.duobao.xxtjd,com.sy4399.xxtjd' AND type='1';
UPDATE game_config SET key_word = '小小英雄,xiaoxiaoyingxiong,xxyx' WHERE pack_name='com.jingmo.yxzb,com.tencent.tmgp.xxyxkp,com.sy4399.yxzb' AND type='1';
UPDATE game_config SET key_word = '星际火线,xingjihuoxian,xjhx' WHERE pack_name='com.tencent.tmgp.h3dstarwars' AND type='1';
UPDATE game_config SET key_word = '新轩辕剑,xinxuanyuanjian,xxyj' WHERE pack_name='com.cyou.xyj.cyou' AND type='1';
UPDATE game_config SET key_word = '妖神记,yaoshenji,ysj' WHERE pack_name='com.tencent.tmgp.ysj' AND type='1';
UPDATE game_config SET key_word = '野蛮人大作战,yemanrendazuozhan,ymrdzz' WHERE pack_name='com.bbqstudio.bbqq,com.bbqstudio.bbqqexp' AND type='1';
UPDATE game_config SET key_word = '硬霸三国,yingbasanguo,ybsg' WHERE pack_name='com.dianhun.IMBA' AND type='1';
UPDATE game_config SET key_word = '英魂之刃,yinghunzhiren,yhzr' WHERE pack_name='com.tencent.tmgp.coslegend,com.netdragon.heroesevolved,com.tq.he.nearme.gamecenter' AND type='1';
UPDATE game_config SET key_word = '英灵召唤师,yinglingzhaohuanshi,ylzhs' WHERE pack_name='com.tencent.tmgp.dragontcg1' AND type='1';
UPDATE game_config SET key_word = '英雄枪战,yingxiongqiangzhan,yxqz' WHERE pack_name='com.jingmo.qzyx2,com.sy4399.qzyx2,com.tencent.tmgp.yxqzkp' AND type='1';
UPDATE game_config SET key_word = '英雄战歌,yingxiongzhange,yxzg' WHERE pack_name='com.tencent.tmgp.yxzg' AND type='1';
UPDATE game_config SET key_word = '一起来飞车,yiqilaifeiche,yqlfc,来飞车' WHERE pack_name='com.wyd.hero.yqlfc.cb1,com.unity.wydsdk.SplashActivity,com.tencent.tmgp.yqlfc' AND type='1';
UPDATE game_config SET key_word = '妖怪三国志-国盗战争,Yo-Kai Sangokushi,yaoguaisanguozhi-guodaozhanzheng,ygsgz-gdzz,国盗りウォーズ' WHERE pack_name='com.Level5.YSG2' AND type='1';
UPDATE game_config SET key_word = '游戏王,Yu-Gi-Oh!,youxiwang,yxw,决斗联盟,juedoulianmeng,yxwjdlm,duel links,日服外服' WHERE pack_name='jp.konami.duellinks,jp.konami.yugiohmobile' AND type='1';
UPDATE game_config SET key_word = '原谅帽大作战,yuanliangmaodazuozhan,ylmdzz' WHERE pack_name='com.ssyar.green' AND type='1';
UPDATE game_config SET key_word = '原始人物語:部落時代,yuanshirenwuyu:buluoshidai,ysrwy:blsd,部落契约,buluoqiyue,blqy' WHERE pack_name='com.ysr.yoogame' AND type='1';
UPDATE game_config SET key_word = '浴血长空,yuxuezhangkong,yxzk' WHERE pack_name='com.tencent.tmgp.warwingscn' AND type='1';
UPDATE game_config SET key_word = '造梦西游4,zaomengxiyou4,zmxy4' WHERE pack_name='org.cocos2dx.zmxy.m4399' AND type='1';
UPDATE game_config SET key_word = '造梦西游OL,zaomengxiyouOL,zmxyOL' WHERE pack_name='com.gwd.zmxyonline,com.tencent.tmgp.zmxyol,org.yjmobile.zmxy' AND type='1';
UPDATE game_config SET key_word = '战地指挥官,zhandezhihuiguan,zdzhg' WHERE pack_name='com.xl.zdzhg.stargame,com.tencent.tmgp.zdzhg' AND type='1';
UPDATE game_config SET key_word = '战斗吧剑灵,zhandoubajianling,zdbjl,Blade&Soul mobile' WHERE pack_name='com.tencent.tmgp.bnsm' AND type='1';
UPDATE game_config SET key_word = '战国志,zhanguozhi,zgz,网易,wangyi,wy' WHERE pack_name='com.netease.h50,com.netease.zgz' AND type='1';
UPDATE game_config SET key_word = '战舰联盟,zhanjianlianmeng,zjlm,舰炮与鱼雷,jianpaoyuyulei' WHERE pack_name='com.loong.jpyyl,com.loong.warship.zl' AND type='1';
UPDATE game_config SET key_word = '战舰猎手,zhanjianlieshou,zjls' WHERE pack_name='com.kongzhong.d183.paycenter,com.tencent.tmgp.zjls2017' AND type='1';
UPDATE game_config SET key_word = '战舰少女R,zhanjianshaonvR,zjsnR' WHERE pack_name='com.hoolai.zjsnr.mi,com.huanmeng.zhanjian2,com.moefantasy.warshipgirls,com.tencent.tmgp.zhanjian2,com.p7game.shipwar.vivo' AND type='1';
UPDATE game_config SET key_word = '战就战,zhanjiuzhan,zjz' WHERE pack_name='com.tencent.tmgp.ftf,com.dygame.fight' AND type='1';
UPDATE game_config SET key_word = '战玲珑,zhanlinglong,zll' WHERE pack_name='com.askj.jtyl5.ewan' AND type='1';
UPDATE game_config SET key_word = '战争怒吼,zhanzhengnuhou,zznh,网易,wangyi,wy' WHERE pack_name='com.netease.zznh.netease' AND type='1';
UPDATE game_config SET key_word = '战争与文明,zhanzhengyuwenming,zzywm' WHERE pack_name='com.tiancity.zzywm.tc,com.tencent.tmgp.tiancity.dom' AND type='1';
UPDATE game_config SET key_word = '召唤与合成,zhaohuanyuhecheng,zhyhc' WHERE pack_name='com.zhaohe.game522' AND type='1';
UPDATE game_config SET key_word = '重装突击,zhongzhuangtuji,zztj,网易,wangyi,wy' WHERE pack_name='com.netease.zztj' AND type='1';
UPDATE game_config SET key_word = '猪场怼怼乐,zhuchangduiduile,zcddl,网易,wangyi,wy' WHERE pack_name='com.netease.zcddl' AND type='1';
UPDATE game_config SET key_word = '诛神成仙,zhushenchengxian,zscx' WHERE pack_name='com.cjgame.qytx.zscx' AND type='1';
UPDATE game_config SET key_word = '自由之战,ziyouzhizhan,zyzz' WHERE pack_name='com.tencent.tmgp.dw.fs.yyb,com.dw.fs' AND type='1';
UPDATE game_config SET key_word = '自由之战2,ziyouzhizhan2,zyzz2' WHERE pack_name='com.tencent.tmgp.fff2,com.gaeamobile.cn.fff2,com.aligames.fff2' AND type='1';
UPDATE game_config SET key_word = '僵尸炮艇:生存大战,Zombie Gunship Survival,jiangshipaoting:shengcundazhan,jspt:scdz,ZG Survival' WHERE pack_name='com.flaregames.zgs' AND type='1';
UPDATE game_config SET key_word = 'IDOLiSH7,アイドリッシュセブン' WHERE pack_name='jp.co.bandainamcoonline.idolish7' AND type='1';
UPDATE game_config SET key_word = 'Battle of Blade,バトル オブ ブレイド' WHERE pack_name='com.square_enix.android_googleplay.BattleofBladesjp' AND type='1';
UPDATE game_config SET key_word = '传送门骑士,传送门骑士手游,chuansongmenqishi,csmqs' WHERE pack_name='com.duoyi.m2csm' AND type='1';
UPDATE game_config SET key_word = 'PUBG MOBILE LITE,刺激战场,绝地求生' WHERE pack_name='com.tencent.iglite' AND type='1';
UPDATE game_config SET key_word = '千年战争,千年战争Aigis,qiannianzhanzheng,qnzz,千年戦争アイギスA' WHERE pack_name='com.dmm.dmmlabo.aigisc' AND type='1';
UPDATE game_config SET key_word = '幻想神域,幻想神域手游,huanxiangshenyu,hxsy,huanxiangshenyushouyou,hxsysy' WHERE pack_name='com.tencent.tmgp.hxsy,com.zlongame.hxsy' AND type='1';
UPDATE game_config SET key_word = 'C.A.T.S.,战车大战,zhanchedazhan,zcdz,CATS: Crash Arena Turbo Stars' WHERE pack_name='com.zeptolab.cats.google' AND type='1';
UPDATE game_config SET key_word = '星之勇者斗恶龙,星のドラゴンクエスト,xingzhiyongzhedouelong,xzyzdel' WHERE pack_name='com.square_enix.hoshinodqjp' AND type='1';
UPDATE game_config SET key_word = '热血传奇,热血传奇-跨服新大陆,rexuechuanqi,rxcq,热血传奇 跨服新大陆,rexuechuanqi kuafuxindalu,rxcq kfxdl' WHERE pack_name='com.tencent.tmgp.rxcq' AND type='1';
UPDATE game_config SET key_word = '刺激战场(体验服),绝地求生:刺激战场(体验服),cijizhanchang(tiyanfu),cjzc(tyf),吃鸡,chiji' WHERE pack_name='com.tencent.tmgp.pubgmhdce' AND type='1';
UPDATE game_config SET key_word = 'Ubisoft Club,育碧' WHERE pack_name='com.ubisoft.uplay' AND type='1';
UPDATE game_config SET key_word = '青石,青石手游,qingshi,qs,Blustone' WHERE pack_name='com.vshower.prd_sr' AND type='1';
UPDATE game_config SET key_word = 'Hackers,黑客,骇客' WHERE pack_name='com.tricksterarts.hackers' AND type='1';
UPDATE game_config SET key_word = 'AxE,액스' WHERE pack_name='com.nexon.axe' AND type='1';
UPDATE game_config SET key_word = '极品飞车:无限狂飙,Need for Speed™ No Limits,jipinfeiche:wuxiankuangbiao,jpfc:wxkb' WHERE pack_name='com.ea.game.nfs14_row' AND type='1';
UPDATE game_config SET key_word = '决战!平安京(海外),Onmyoji Arena,juezhan!pinganjing(haiwai),jz!paj(hw),决战!平安京(日服),決戰平安京,juezhan!pinganjing(rifu),jz!paj(rf),决战！平安京(日服),juezhan！pinganjing(rifu),jz！paj(rf),决战！平安京(海外版),juezhan！pinganjing(haiwaiban),jz！paj(hwb),网易,wangyi,wy' WHERE pack_name='com.netease.g78na.gb,com.netease.g78na.tw' AND type='1';
UPDATE game_config SET key_word = '混沌与秩序2：救赎,Order and Chaos 2: Redemption,hundunyuzhixu2：jiushu,hdyzx2：js,混沌与秩序2,hundunyuzhixu2,hdyzx2' WHERE pack_name='com.gameloft.android.ANMP.GloftO2HM' AND type='1';
UPDATE game_config SET key_word = '梦幻之星网路版 2 es,Phantasy Star Online 2 es,menghuanzhixingwangluban 2 es,mhzxwlb 2 es,ファンタシースターオンライン2 es,Phantasy Star Online2 es,pso2es'WHERE pack_name = 'com.sega.PhantasyStarOnline2es' AND type='1';
UPDATE game_config SET key_word = '植物大战僵尸™英雄,Plants vs. Zombies™ Heroes,zhiwudazhanjiangshi™yingxiong,zwdzjs™yx' WHERE pack_name='com.ea.gp.pvzheroes' AND type='1';
UPDATE game_config SET key_word = '公主连接!Re:Dive(台服),Princess Connect! Re:Dive(TW),gongzhulianjie!Re:Dive(taifu),gzlj!Re:Dive(tf),超異域公主連結!Re:Dive,Princess Connect! Re:Dive' WHERE pack_name='tw.sonet.princessconnect' AND type='1';
UPDATE game_config SET key_word = '求生之王:绝地大逃杀,Royale BattleGrounds,qiushengzhiwang:juededataosha,qszw:jddts,求生之王:大逃杀,qiushengzhiwang:dataosha,qszw:dts,大吉大利今晚吃鸡,CarsBattle2: Royale BattleGrounds' WHERE pack_name='com.funcity.carsbattletwo' AND type='1';
UPDATE game_config SET key_word = '三国志曹操传 online,Sangokushi Sousouden Online,sanguozhicaocaochuan online,sgzccc online' WHERE pack_name='com.nexon.caocao.taiwan' AND type='1';



